//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Gbs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Gbs.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string AutoModeView_Accuracy_Name {
            get {
                return ResourceManager.GetString("AutoModeView_Accuracy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string AutoModeView_Observation_Name {
            get {
                return ResourceManager.GetString("AutoModeView_Observation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy must be greater or equal {0}..
        /// </summary>
        public static string AutoModeViewModel_Accuracy_ValidValue {
            get {
                return ResourceManager.GetString("AutoModeViewModel_Accuracy_ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation time must be greater or equal {0}..
        /// </summary>
        public static string AutoModeViewModel_Observation_ValidValue {
            get {
                return ResourceManager.GetString("AutoModeViewModel_Observation_ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string AutoModeViewModel_ObservationUnit_Name {
            get {
                return ResourceManager.GetString("AutoModeViewModel_ObservationUnit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode start failed: {0}.
        /// </summary>
        public static string AutoModeViewModel_StartFailed {
            get {
                return ResourceManager.GetString("AutoModeViewModel_StartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string FixedModeView_Accuracy_Name {
            get {
                return ResourceManager.GetString("FixedModeView_Accuracy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string FixedModeView_Altitude_Name {
            get {
                return ResourceManager.GetString("FixedModeView_Altitude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string FixedModeView_Latitude_Name {
            get {
                return ResourceManager.GetString("FixedModeView_Latitude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string FixedModeView_Longitude_Name {
            get {
                return ResourceManager.GetString("FixedModeView_Longitude_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy must be greater or equal {0}..
        /// </summary>
        public static string FixedModeViewModel_Accuracy_ValidValue {
            get {
                return ResourceManager.GetString("FixedModeViewModel_Accuracy_ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude must be greater or equal {0}..
        /// </summary>
        public static string FixedModeViewModel_Altitude_ValidValue {
            get {
                return ResourceManager.GetString("FixedModeViewModel_Altitude_ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be greater or equal {0}..
        /// </summary>
        public static string FixedModeViewModel_Latitude_ValidValue {
            get {
                return ResourceManager.GetString("FixedModeViewModel_Latitude_ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be greater or equal {0}..
        /// </summary>
        public static string FixedModeViewModel_Longitude_ValidValue {
            get {
                return ResourceManager.GetString("FixedModeViewModel_Longitude_ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed mode start failed: {0}.
        /// </summary>
        public static string FixedModeViewModel_StartFailed {
            get {
                return ResourceManager.GetString("FixedModeViewModel_StartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FlightGbsViewModel_AutoMode_CloseButtonText {
            get {
                return ResourceManager.GetString("FlightGbsViewModel_AutoMode_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string FlightGbsViewModel_AutoMode_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FlightGbsViewModel_AutoMode_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Mode.
        /// </summary>
        public static string FlightGbsViewModel_AutoMode_Title {
            get {
                return ResourceManager.GetString("FlightGbsViewModel_AutoMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FlightGbsViewModel_FixedMode_CloseButtonText {
            get {
                return ResourceManager.GetString("FlightGbsViewModel_FixedMode_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string FlightGbsViewModel_FixedMode_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FlightGbsViewModel_FixedMode_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Mode.
        /// </summary>
        public static string FlightGbsViewModel_FixedMode_Title {
            get {
                return ResourceManager.GetString("FlightGbsViewModel_FixedMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground base station.
        /// </summary>
        public static string FlightGbsViewModel_Title {
            get {
                return ResourceManager.GetString("FlightGbsViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNSS Altitude: {0}.
        /// </summary>
        public static string GbsAnchor_GNSS_Altitude {
            get {
                return ResourceManager.GetString("GbsAnchor_GNSS_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0}.
        /// </summary>
        public static string GbsAnchor_Latitude {
            get {
                return ResourceManager.GetString("GbsAnchor_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude: {0}.
        /// </summary>
        public static string GbsAnchor_Longitude {
            get {
                return ResourceManager.GetString("GbsAnchor_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Base Station.
        /// </summary>
        public static string GbsAnchor_Title {
            get {
                return ResourceManager.GetString("GbsAnchor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N\A.
        /// </summary>
        public static string GbsRttItem_ValueNotAvailable {
            get {
                return ResourceManager.GetString("GbsRttItem_ValueNotAvailable", resourceCulture);
            }
        }
    }
}
