//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Api.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number with optional suffix (K, M, G).
        /// </summary>
        internal static string MavParamInfo_ValidationException_InvalidFormat {
            get {
                return ResourceManager.GetString("MavParamInfo_ValidationException_InvalidFormat", resourceCulture);
            }
        }

        internal static string FlightWidgetAction_CreateCommand_Title {
            get {
                return ResourceManager.GetString("FlightWidgetAction_CreateCommand_Title", resourceCulture);
            }
        }

        internal static string ConfigureTelemetryAction_Header {
            get {
                return ResourceManager.GetString("ConfigureTelemetryAction_Header", resourceCulture);
            }
        }

        internal static string ConfigureTelemetryAction_Description {
            get {
                return ResourceManager.GetString("ConfigureTelemetryAction_Description", resourceCulture);
            }
        }

        internal static string ConfigureTelemetryAction_DialogTitle {
            get {
                return ResourceManager.GetString("ConfigureTelemetryAction_DialogTitle", resourceCulture);
            }
        }

        internal static string ConfigureTelemetryAction_DialogPrimaryButtonText {
            get {
                return ResourceManager.GetString("ConfigureTelemetryAction_DialogPrimaryButtonText", resourceCulture);
            }
        }

        internal static string ConfigureTelemetryAction_DialogCloseButtonText {
            get {
                return ResourceManager.GetString("ConfigureTelemetryAction_DialogCloseButtonText", resourceCulture);
            }
        }

        internal static string ConfigureTelemetryDialogViewModel_SelectAll_Header {
            get {
                return ResourceManager.GetString("ConfigureTelemetryDialogViewModel_SelectAll_Header", resourceCulture);
            }
        }

        internal static string ConfigureTelemetryDialogViewModel_ClearSelection_Header {
            get {
                return ResourceManager.GetString("ConfigureTelemetryDialogViewModel_ClearSelection_Header", resourceCulture);
            }
        }

        internal static string SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff", resourceCulture);
            }
        }

        internal static string SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel", resourceCulture);
            }
        }

        internal static string UavWidgetViewModel_SetAltitudeDialog_Title {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_SetAltitudeDialog_Title", resourceCulture);
            }
        }

        internal static string AutoModeAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("AutoModeAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string AutoModeAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("AutoModeAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string RefreshMissionAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("RefreshMissionAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string RefreshMissionAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("RefreshMissionAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string StartMissionAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("StartMissionAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string StartMissionAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("StartMissionAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string GuidedAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("GuidedAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string GuidedAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("GuidedAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string RtlAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("RtlAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string RtlAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("RtlAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string LandAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("LandAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string LandAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("LandAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string TakeOffAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("TakeOffAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string TakeOffAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("TakeOffAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string GotoAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("GotoAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string GotoAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("GotoAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string RoiAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("RoiAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string RoiAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("RoiAction_TryCreateAction_Description", resourceCulture);
            }
        }

        internal static string FindDroneAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("FindDroneAction_TryCreateAction_Header", resourceCulture);
            }
        }

        internal static string FindDroneAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("FindDroneAction_TryCreateAction_Description", resourceCulture);
            }
        }
    }
}
