//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Drones.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ParamItemView_PinToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParamItemView_PinToggleButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParamItemView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParamItemView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParamItemView_UpdateButton_Text {
            get {
                return ResourceManager.GetString("ParamItemView_UpdateButton_Text", resourceCulture);
            }
        }
        
        public static string ParamItemView_WriteButton_ToolTip {
            get {
                return ResourceManager.GetString("ParamItemView_WriteButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParamItemView_WriteButton_Text {
            get {
                return ResourceManager.GetString("ParamItemView_WriteButton_Text", resourceCulture);
            }
        }
        
        public static string ParamItemView_InlineNotification_RebootRequired {
            get {
                return ResourceManager.GetString("ParamItemView_InlineNotification_RebootRequired", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_StarsToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarsToggleButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_PinsOffButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_PinsOffButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageViewModel_Search {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Search", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageViewModel_Total {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Total", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_StarButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_Content {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Content", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_Title {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Title", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_CloseButtonText", resourceCulture);
            }
        }
        
        public static string Unit_Byte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Byte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Kilobyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Kilobyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Megabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Megabyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Gigabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Gigabyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Terabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Terabyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_UploadingDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_UploadingDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_UploadingDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_UploadingDialog_Message", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_DownloadDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_DownloadDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_DownloadDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_DownloadDialog_Message", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_FileDownloadedSuccessfully {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_FileDownloadedSuccessfully", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RemoveDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RemoveDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RemoveDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RemoveDialog_Message", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_BurstDownloadDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_BurstDownloadDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_BurstDownloadDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string NotANumber {
            get {
                return ResourceManager.GetString("NotANumber", resourceCulture);
            }
        }
        
        public static string MissionProgressView_Title {
            get {
                return ResourceManager.GetString("MissionProgressView_Title", resourceCulture);
            }
        }
        
        public static string MissionProgressView_SubStatusText {
            get {
                return ResourceManager.GetString("MissionProgressView_SubStatusText", resourceCulture);
            }
        }
        
        public static string MissionProgressView_MissionDistanceRTT {
            get {
                return ResourceManager.GetString("MissionProgressView_MissionDistanceRTT", resourceCulture);
            }
        }
        
        public static string MissionProgressView_TotalDistanceRTT {
            get {
                return ResourceManager.GetString("MissionProgressView_TotalDistanceRTT", resourceCulture);
            }
        }
        
        public static string MissionProgressView_HomeDistance {
            get {
                return ResourceManager.GetString("MissionProgressView_HomeDistance", resourceCulture);
            }
        }
        
        public static string MissionProgressView_TargetDistance {
            get {
                return ResourceManager.GetString("MissionProgressView_TargetDistance", resourceCulture);
            }
        }
        
        public static string MissionProgressView_DownLoadingMission {
            get {
                return ResourceManager.GetString("MissionProgressView_DownLoadingMission", resourceCulture);
            }
        }
        
        public static string UavRttItem_Mode {
            get {
                return ResourceManager.GetString("UavRttItem_Mode", resourceCulture);
            }
        }
        
        public static string UavRttItem_Altitude {
            get {
                return ResourceManager.GetString("UavRttItem_Altitude", resourceCulture);
            }
        }
        
        public static string UavRttItem_Velocity {
            get {
                return ResourceManager.GetString("UavRttItem_Velocity", resourceCulture);
            }
        }
        
        public static string UavRttItem_Azimuth {
            get {
                return ResourceManager.GetString("UavRttItem_Azimuth", resourceCulture);
            }
        }
        
        public static string UavRttItem_Battery {
            get {
                return ResourceManager.GetString("UavRttItem_Battery", resourceCulture);
            }
        }
        
        public static string UavRttItem_GNSS {
            get {
                return ResourceManager.GetString("UavRttItem_GNSS", resourceCulture);
            }
        }
        
        public static string UavRttItem_Link {
            get {
                return ResourceManager.GetString("UavRttItem_Link", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_StatusText_Armed {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_Armed", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_StatusText_PullUp {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_PullUp", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_StatusText_DisArmed {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_DisArmed", resourceCulture);
            }
        }
        
        public static string FlightPageViewModel_Title {
            get {
                return ResourceManager.GetString("FlightPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixType2dFix {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixType2dFix", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeRtkFloat {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeRtkFloat", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeRtkFixed {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeRtkFixed", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeDgps {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeDgps", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypePpp {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypePpp", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixType3dFix {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixType3dFix", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeStatic {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeStatic", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeNoGps {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeNoGps", resourceCulture);
            }
        }
        
        public static string SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff", resourceCulture);
            }
        }
        
        public static string SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel", resourceCulture);
            }
        }
        
        public static string MissionProgressViewModel_MissionFlightTime_Symbol {
            get {
                return ResourceManager.GetString("MissionProgressViewModel_MissionFlightTime_Symbol", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Watermark_Local {
            get {
                return ResourceManager.GetString("FileBrowserView_Watermark_Local", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Watermark_Remote {
            get {
                return ResourceManager.GetString("FileBrowserView_Watermark_Remote", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Button_Download_Content {
            get {
                return ResourceManager.GetString("FileBrowserView_Button_Download_Content", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Button_BurstDownload_Content {
            get {
                return ResourceManager.GetString("FileBrowserView_Button_BurstDownload_Content", resourceCulture);
            }
        }
        
        public static string UnpinAllParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UnpinAllParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string WriteParamCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("WriteParamCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string WritePatamCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("WritePatamCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string UnpinAllParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UnpinAllParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string StopUpdateParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("StopUpdateParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string StopUpdateParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("StopUpdateParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string UpdateParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UpdateParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string UpdateParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UpdateParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ReadParamCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ReadParamCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ReadParamCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ReadParamCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenMavParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenMavParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenMavParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenMavParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string HomePageParamsDeviceItemAction_ActionViewModel_Header {
            get {
                return ResourceManager.GetString("HomePageParamsDeviceItemAction_ActionViewModel_Header", resourceCulture);
            }
        }
        
        public static string HomePageParamsDeviceItemAction_ActionViewModel_Description {
            get {
                return ResourceManager.GetString("HomePageParamsDeviceItemAction_ActionViewModel_Description", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SavePacketMessagesDialog_Title {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_Title", resourceCulture);
            }
        }
        
        public static string SavePacketMessagesDialogView_Separator_Tab {
            get {
                return ResourceManager.GetString("SavePacketMessagesDialogView_Separator_Tab", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ToolTip_Save {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_Save", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ToolTip_ClearAll {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_ClearAll", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ToolTip_PlayPause {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_PlayPause", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Date {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Date", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Source {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Source", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Type {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Type", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Message {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Message", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ExpanderFilterBySources_Header {
            get {
                return ResourceManager.GetString("PacketViewerView_ExpanderFilterBySources_Header", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ExpanderFilterByTypes_Header {
            get {
                return ResourceManager.GetString("PacketViewerView_ExpanderFilterByTypes_Header", resourceCulture);
            }
        }
        
        public static string PacketViewerView_Filters_CheckAll {
            get {
                return ResourceManager.GetString("PacketViewerView_Filters_CheckAll", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SavePacketMessagesDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_CloseButtonText", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SavePacketMessagesDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_Message", resourceCulture);
            }
        }
        
        public static string OpenFlightModeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenFlightModeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenFlightModeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenFlightModeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenFileBrowserCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenFileBrowserCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenFileBrowserCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenFileBrowserCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenPacketViewerCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenPacketViewerCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenPacketViewerCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenPacketViewerCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Velocity {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Velocity", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Altitude {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Altitude", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Compass {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Compass", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Vibration {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Vibration", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_Title", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_SetAltitudeDialog_Title {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_SetAltitudeDialog_Title", resourceCulture);
            }
        }
        
        public static string MavParamsPageView_AwaitingScreen_Header {
            get {
                return ResourceManager.GetString("MavParamsPageView_AwaitingScreen_Header", resourceCulture);
            }
        }
        
        public static string MavParamsPageView_AwaitingScreen_Description {
            get {
                return ResourceManager.GetString("MavParamsPageView_AwaitingScreen_Description", resourceCulture);
            }
        }
        
        public static string MavParamsPageView_CancelButton_Content {
            get {
                return ResourceManager.GetString("MavParamsPageView_CancelButton_Content", resourceCulture);
            }
        }
        
        public static string MavParamsPageView_Loading_Text {
            get {
                return ResourceManager.GetString("MavParamsPageView_Loading_Text", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_Title {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_Title", resourceCulture);
            }
        }
        
        public static string MavParamsPageViewModel_Title {
            get {
                return ResourceManager.GetString("MavParamsPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string ClearAllPacketsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ClearAllPacketsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ClearAllPacketsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ClearAllPacketsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ExportPacketsToCsvCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ExportPacketsToCsvCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ExportPacketsToCsvCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ExportPacketsToCsvCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string RenameItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RenameItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string RenameItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RenameItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string FileBrowserView_AwaitingScreen_Header {
            get {
                return ResourceManager.GetString("FileBrowserView_AwaitingScreen_Header", resourceCulture);
            }
        }
        
        public static string FileBrowserView_AwaitingScreen_Description {
            get {
                return ResourceManager.GetString("FileBrowserView_AwaitingScreen_Description", resourceCulture);
            }
        }
        
        public static string RemoveItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RemoveItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string RemoveItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RemoveItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string CalculateCrc32Command_CommandInfo_Description {
            get {
                return ResourceManager.GetString("CalculateCrc32Command_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string CalculateCrc32Command_CommandInfo_Name {
            get {
                return ResourceManager.GetString("CalculateCrc32Command_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string CreateDirectoryCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("CreateDirectoryCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string CreateDirectoryCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("CreateDirectoryCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string BurstDownloadItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("BurstDownloadItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string BurstDownloadItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("BurstDownloadItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string DownloadItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("DownloadItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string DownloadItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("DownloadItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string UploadItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UploadItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string UploadItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UploadItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string FindFileOnLocalCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("FindFileOnLocalCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string FindFileOnLocalCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("FindFileOnLocalCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string SetupPageViewModel_Title {
            get {
                return ResourceManager.GetString("SetupPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeViewModel_Name {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_Name", resourceCulture);
            }
        }
        
        public static string ChangeFrameTypeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeFrameTypeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ChangeFrameTypeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeFrameTypeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeView_Loader_Header {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_Loader_Header", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeView_Loader_Description {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_Loader_Description", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeView_CurrentFrame {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_CurrentFrame", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeView_FrameMetadata {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_FrameMetadata", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeView_ApplyFrame {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_ApplyFrame", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeViewModel_ApplyConfirmation_Title {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_ApplyConfirmation_Title", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeViewModel_ApplyConfirmation_Message {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_ApplyConfirmation_Message", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeViewModel_CurrentFrame_Unknown {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_CurrentFrame_Unknown", resourceCulture);
            }
        }
        
        public static string OpenSetupCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenSetupCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenSetupCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenSetupCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeView_CurrentFrame_Refresh {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_CurrentFrame_Refresh", resourceCulture);
            }
        }
        
        public static string SetupFrameTypeView_CurrentFrame_Meta {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_CurrentFrame_Meta", resourceCulture);
            }
        }
        
        public static string MissionProgressView_RefreshButton_Text {
            get {
                return ResourceManager.GetString("MissionProgressView_RefreshButton_Text", resourceCulture);
            }
        }
        
        public static string MissionProgressView_DownloadButton_Text {
            get {
                return ResourceManager.GetString("MissionProgressView_DownloadButton_Text", resourceCulture);
            }
        }
        
        public static string SetupMotorsView_TestDuration {
            get {
                return ResourceManager.GetString("SetupMotorsView_TestDuration", resourceCulture);
            }
        }
        
        public static string SetupMotorsView_DurationLabel_TimeUnit {
            get {
                return ResourceManager.GetString("SetupMotorsView_DurationLabel_TimeUnit", resourceCulture);
            }
        }
        
        public static string MotorItemView_Label_MotorId {
            get {
                return ResourceManager.GetString("MotorItemView_Label_MotorId", resourceCulture);
            }
        }
        
        public static string MotorItemView_MonitoringLabel_Servo {
            get {
                return ResourceManager.GetString("MotorItemView_MonitoringLabel_Servo", resourceCulture);
            }
        }
        
        public static string MotorItemView_MonitoringLabel_Pwm {
            get {
                return ResourceManager.GetString("MotorItemView_MonitoringLabel_Pwm", resourceCulture);
            }
        }
        
        public static string MotorItemView_ToolTip_StartStop {
            get {
                return ResourceManager.GetString("MotorItemView_ToolTip_StartStop", resourceCulture);
            }
        }
        
        public static string SetupMotorsViewModel_Name {
            get {
                return ResourceManager.GetString("SetupMotorsViewModel_Name", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_N {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_N", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_NE {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_NE", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_E {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_E", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_SE {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_SE", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_S {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_S", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_SW {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_SW", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_W {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_W", resourceCulture);
            }
        }
        
        public static string HeadingScaleItem_Direction_NW {
            get {
                return ResourceManager.GetString("HeadingScaleItem_Direction_NW", resourceCulture);
            }
        }
        
        public static string BurstDownloadDialogView_Description_Text {
            get {
                return ResourceManager.GetString("BurstDownloadDialogView_Description_Text", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_BatteryRttBox_BatteryCharge_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_BatteryRttBox_BatteryCharge_Header", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_BatteryRttBox_BatteryAmperage_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_BatteryRttBox_BatteryAmperage_Header", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_BatteryRttBox_BatteryVoltage_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_BatteryRttBox_BatteryVoltage_Header", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_BatteryRttBox_BatteryConsumed_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_BatteryRttBox_BatteryConsumed_Header", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_GnssRttBox_SatellitesCount_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_GnssRttBox_SatellitesCount_Header", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_GnssRttBox_Hdop_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_GnssRttBox_Hdop_Header", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_GnssRttBox_Vdop_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_GnssRttBox_Vdop_Header", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_GnssRttBox_Mode_Header {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_GnssRttBox_Mode_Header", resourceCulture);
            }
        }
        
        public static string HeadingUavIndicatorViewModel_Heading {
            get {
                return ResourceManager.GetString("HeadingUavIndicatorViewModel_Heading", resourceCulture);
            }
        }
        
        public static string HeadingUavIndicatorViewModel_Heading_Short {
            get {
                return ResourceManager.GetString("HeadingUavIndicatorViewModel_Heading_Short", resourceCulture);
            }
        }
        
        public static string HomeAzimuthUavIndicatorViewModel_HomeAzimuth {
            get {
                return ResourceManager.GetString("HomeAzimuthUavIndicatorViewModel_HomeAzimuth", resourceCulture);
            }
        }
        
        public static string HomeAzimuthUavIndicatorViewModel_HomeAzimuth_Short {
            get {
                return ResourceManager.GetString("HomeAzimuthUavIndicatorViewModel_HomeAzimuth_Short", resourceCulture);
            }
        }
        
        public static string VelocityUavIndicatorViewModel_Velocity_Short {
            get {
                return ResourceManager.GetString("VelocityUavIndicatorViewModel_Velocity_Short", resourceCulture);
            }
        }
        
        public static string AngleUavRttIndicatorViewModel_Angle {
            get {
                return ResourceManager.GetString("AngleUavRttIndicatorViewModel_Angle", resourceCulture);
            }
        }
        
        public static string AltitudeUavIndicatorViewModel_Agl {
            get {
                return ResourceManager.GetString("AltitudeUavIndicatorViewModel_Agl", resourceCulture);
            }
        }
        
        public static string AltitudeUavIndicatorViewModel_Msl {
            get {
                return ResourceManager.GetString("AltitudeUavIndicatorViewModel_Msl", resourceCulture);
            }
        }
        
        public static string AngleUavRttIndicatorViewModel_Pitch {
            get {
                return ResourceManager.GetString("AngleUavRttIndicatorViewModel_Pitch", resourceCulture);
            }
        }
        
        public static string AngleUavRttIndicatorViewModel_Roll {
            get {
                return ResourceManager.GetString("AngleUavRttIndicatorViewModel_Roll", resourceCulture);
            }
        }
        
        public static string AddTelemetryItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("AddTelemetryItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string AddTelemetryItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("AddTelemetryItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string RemoveTelemetryItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RemoveTelemetryItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string RemoveTelemetryItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RemoveTelemetryItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ResetTelemetryItemsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ResetTelemetryItemsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ResetTelemetryItemsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ResetTelemetryItemsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string AddTelemetryDisplayItemView_AddIndicatorButton_ToolTip {
            get {
                return ResourceManager.GetString("AddTelemetryDisplayItemView_AddIndicatorButton_ToolTip", resourceCulture);
            }
        }
        
        public static string TelemetrySectionView_DoneButton_ToolTip {
            get {
                return ResourceManager.GetString("TelemetrySectionView_DoneButton_ToolTip", resourceCulture);
            }
        }
        
        public static string TelemetrySectionView_ConfirmEditingMenuItem_Header {
            get {
                return ResourceManager.GetString("TelemetrySectionView_ConfirmEditingMenuItem_Header", resourceCulture);
            }
        }
        
        public static string TelemetrySectionView_EditIndicatorsMenuItem_Header {
            get {
                return ResourceManager.GetString("TelemetrySectionView_EditIndicatorsMenuItem_Header", resourceCulture);
            }
        }
        
        public static string TelemetrySectionView_ResetButton_ToolTip {
            get {
                return ResourceManager.GetString("TelemetrySectionView_ResetButton_ToolTip", resourceCulture);
            }
        }
        
        public static string TelemetrySectionView_ResetMenuItem_Header {
            get {
                return ResourceManager.GetString("TelemetrySectionView_ResetMenuItem_Header", resourceCulture);
            }
        }
        
        public static string TelemetrySectionViewModel_ConfigureTelemetryDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("TelemetrySectionViewModel_ConfigureTelemetryDialog_CloseButtonText", resourceCulture);
            }
        }
        
        public static string TelemetrySectionViewModel_ConfigureTelemetryDialog_Title {
            get {
                return ResourceManager.GetString("TelemetrySectionViewModel_ConfigureTelemetryDialog_Title", resourceCulture);
            }
        }
        
        public static string AutoModeAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("AutoModeAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string AutoModeAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("AutoModeAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string GuidedAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("GuidedAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string GuidedAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("GuidedAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string RtlAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("RtlAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string RtlAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("RtlAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string LandAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("LandAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string LandAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("LandAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string TakeOffAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("TakeOffAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string TakeOffAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("TakeOffAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string GotoAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("GotoAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string GotoAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("GotoAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string RoiAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("RoiAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string RoiAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("RoiAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string FindDroneAction_TryCreateAction_Header {
            get {
                return ResourceManager.GetString("FindDroneAction_TryCreateAction_Header", resourceCulture);
            }
        }
        
        public static string FindDroneAction_TryCreateAction_Description {
            get {
                return ResourceManager.GetString("FindDroneAction_TryCreateAction_Description", resourceCulture);
            }
        }
        
        public static string FlightModePageView_WorkspaceItem_ActionsHeader {
            get {
                return ResourceManager.GetString("FlightModePageView_WorkspaceItem_ActionsHeader", resourceCulture);
            }
        }
    }
}
