//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Drones.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DialogPageViewModel_Title {
            get {
                return ResourceManager.GetString("DialogPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string DocumentPageViewModel_Title {
            get {
                return ResourceManager.GetString("DocumentPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_PinToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_PinToggleButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_UpdateButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_WriteButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_WriteButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton", resourceCulture);
            }
        }
        
        public static string ParametersEditorParameterView_RebootRequired {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_RebootRequired", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_StarsToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarsToggleButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_PinsOffButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_PinsOffButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageViewModel_Search {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Search", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageViewModel_Total {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Total", resourceCulture);
            }
        }
        
        public static string ParametersEditorPageView_StarButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarButton_ToolTip", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_Content {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Content", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_Title {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Title", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string ParamPageViewModel_DataLossDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_CloseButtonText", resourceCulture);
            }
        }
        
        public static string Unit_Byte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Byte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Kilobyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Kilobyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Megabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Megabyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Gigabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Gigabyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string Unit_Terabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Terabyte_Abbreviation", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_UploadingDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_UploadingDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_UploadingDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_UploadingDialog_Message", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_DownloadDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_DownloadDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_DownloadDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_DownloadDialog_Message", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_FileDownloadedSuccessfully {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_FileDownloadedSuccessfully", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RemoveDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RemoveDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RemoveDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RemoveDialog_Message", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_BurstDownloadDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_BurstDownloadDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_BurstDownloadDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string MavParamsPageViewModel_DeviceName_Unknown {
            get {
                return ResourceManager.GetString("MavParamsPageViewModel_DeviceName_Unknown", resourceCulture);
            }
        }
        
        public static string NotANumber {
            get {
                return ResourceManager.GetString("NotANumber", resourceCulture);
            }
        }
        
        public static string MissionProgressView_Title {
            get {
                return ResourceManager.GetString("MissionProgressView_Title", resourceCulture);
            }
        }
        
        public static string MissionProgressView_SubStatusText {
            get {
                return ResourceManager.GetString("MissionProgressView_SubStatusText", resourceCulture);
            }
        }
        
        public static string MissionProgressView_MissionDistanceRTT {
            get {
                return ResourceManager.GetString("MissionProgressView_MissionDistanceRTT", resourceCulture);
            }
        }
        
        public static string MissionProgressView_TotalDistanceRTT {
            get {
                return ResourceManager.GetString("MissionProgressView_TotalDistanceRTT", resourceCulture);
            }
        }
        
        public static string MissionProgressView_HomeDistance {
            get {
                return ResourceManager.GetString("MissionProgressView_HomeDistance", resourceCulture);
            }
        }
        
        public static string MissionProgressView_TargetDistance {
            get {
                return ResourceManager.GetString("MissionProgressView_TargetDistance", resourceCulture);
            }
        }
        
        public static string MissionProgressView_DownLoadingMission {
            get {
                return ResourceManager.GetString("MissionProgressView_DownLoadingMission", resourceCulture);
            }
        }
        
        public static string UavAction_AutoMode_Name {
            get {
                return ResourceManager.GetString("UavAction_AutoMode_Name", resourceCulture);
            }
        }
        
        public static string UavAction_GuidedMode {
            get {
                return ResourceManager.GetString("UavAction_GuidedMode", resourceCulture);
            }
        }
        
        public static string UavAction_TakeOff {
            get {
                return ResourceManager.GetString("UavAction_TakeOff", resourceCulture);
            }
        }
        
        public static string UavAction_Rtl_Name {
            get {
                return ResourceManager.GetString("UavAction_Rtl_Name", resourceCulture);
            }
        }
        
        public static string UavAction_Land {
            get {
                return ResourceManager.GetString("UavAction_Land", resourceCulture);
            }
        }
        
        public static string UavAction_StartMission {
            get {
                return ResourceManager.GetString("UavAction_StartMission", resourceCulture);
            }
        }
        
        public static string UavAction_StartMission_Description {
            get {
                return ResourceManager.GetString("UavAction_StartMission_Description", resourceCulture);
            }
        }
        
        public static string UavRttItem_Mode {
            get {
                return ResourceManager.GetString("UavRttItem_Mode", resourceCulture);
            }
        }
        
        public static string UavRttItem_Altitude {
            get {
                return ResourceManager.GetString("UavRttItem_Altitude", resourceCulture);
            }
        }
        
        public static string UavRttItem_Velocity {
            get {
                return ResourceManager.GetString("UavRttItem_Velocity", resourceCulture);
            }
        }
        
        public static string UavRttItem_Azimuth {
            get {
                return ResourceManager.GetString("UavRttItem_Azimuth", resourceCulture);
            }
        }
        
        public static string UavRttItem_Battery {
            get {
                return ResourceManager.GetString("UavRttItem_Battery", resourceCulture);
            }
        }
        
        public static string UavRttItem_GNSS {
            get {
                return ResourceManager.GetString("UavRttItem_GNSS", resourceCulture);
            }
        }
        
        public static string UavRttItem_Link {
            get {
                return ResourceManager.GetString("UavRttItem_Link", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_StatusText_Armed {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_Armed", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_StatusText_PullUp {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_PullUp", resourceCulture);
            }
        }
        
        public static string UavWidgetViewModel_StatusText_DisArmed {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_DisArmed", resourceCulture);
            }
        }
        
        public static string FlightPageViewModel_Title {
            get {
                return ResourceManager.GetString("FlightPageViewModel_Title", resourceCulture);
            }
        }
        
        public static string UavAction_TakeOff_Description {
            get {
                return ResourceManager.GetString("UavAction_TakeOff_Description", resourceCulture);
            }
        }
        
        public static string UavAction_Rtl_Description {
            get {
                return ResourceManager.GetString("UavAction_Rtl_Description", resourceCulture);
            }
        }
        
        public static string UavAction_Land_Description {
            get {
                return ResourceManager.GetString("UavAction_Land_Description", resourceCulture);
            }
        }
        
        public static string UavAction_AutoMode_Description {
            get {
                return ResourceManager.GetString("UavAction_AutoMode_Description", resourceCulture);
            }
        }
        
        public static string UavAction_GuidedMode_Description {
            get {
                return ResourceManager.GetString("UavAction_GuidedMode_Description", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixType2dFix {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixType2dFix", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeRtkFloat {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeRtkFloat", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeRtkFixed {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeRtkFixed", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeDgps {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeDgps", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypePpp {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypePpp", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixType3dFix {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixType3dFix", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeStatic {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeStatic", resourceCulture);
            }
        }
        
        public static string GpsFixType_GpsFixTypeNoGps {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeNoGps", resourceCulture);
            }
        }
        
        public static string SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff", resourceCulture);
            }
        }
        
        public static string SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel", resourceCulture);
            }
        }
        
        public static string MissionProgressViewModel_MissionFlightTime_Symbol {
            get {
                return ResourceManager.GetString("MissionProgressViewModel_MissionFlightTime_Symbol", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Watermark_Local {
            get {
                return ResourceManager.GetString("FileBrowserView_Watermark_Local", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Watermark_Remote {
            get {
                return ResourceManager.GetString("FileBrowserView_Watermark_Remote", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Button_Download_Content {
            get {
                return ResourceManager.GetString("FileBrowserView_Button_Download_Content", resourceCulture);
            }
        }
        
        public static string FileBrowserView_Button_BurstDownload_Content {
            get {
                return ResourceManager.GetString("FileBrowserView_Button_BurstDownload_Content", resourceCulture);
            }
        }
        
        public static string UnpinAllParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UnpinAllParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string WriteParamCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("WriteParamCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string WritePatamCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("WritePatamCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string UnpinAllParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UnpinAllParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string StopUpdateParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("StopUpdateParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string StopUpdateParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("StopUpdateParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string UpdateParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UpdateParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string UpdateParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UpdateParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string ReadParamCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ReadParamCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string ReadParamCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ReadParamCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenMavParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenMavParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenMavParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenMavParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string HomePageParamsDeviceItemAction_ActionViewModel_Header {
            get {
                return ResourceManager.GetString("HomePageParamsDeviceItemAction_ActionViewModel_Header", resourceCulture);
            }
        }
        
        public static string HomePageParamsDeviceItemAction_ActionViewModel_Description {
            get {
                return ResourceManager.GetString("HomePageParamsDeviceItemAction_ActionViewModel_Description", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SavePacketMessagesDialog_Title {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_Title", resourceCulture);
            }
        }
        
        public static string SavePacketMessagesDialogView_Separator_Tab {
            get {
                return ResourceManager.GetString("SavePacketMessagesDialogView_Separator_Tab", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ToolTip_Save {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_Save", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ToolTip_ClearAll {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_ClearAll", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ToolTip_PlayPause {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_PlayPause", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Date {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Date", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Source {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Source", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Type {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Type", resourceCulture);
            }
        }
        
        public static string PacketMessageViewModel_CsvColumn_Message {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Message", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ExpanderFilterBySources_Header {
            get {
                return ResourceManager.GetString("PacketViewerView_ExpanderFilterBySources_Header", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ExpanderFilterByTypes_Header {
            get {
                return ResourceManager.GetString("PacketViewerView_ExpanderFilterByTypes_Header", resourceCulture);
            }
        }
        
        public static string PacketViewerView_Filters_CheckAll {
            get {
                return ResourceManager.GetString("PacketViewerView_Filters_CheckAll", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SavePacketMessagesDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_CloseButtonText", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SavePacketMessagesDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_Title", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        public static string FileBrowserViewModel_RenameDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_Message", resourceCulture);
            }
        }
        
        public static string OpenFlightModeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenFlightModeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenFlightModeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenFlightModeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenFileBrowserCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenFileBrowserCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenFileBrowserCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenFileBrowserCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string OpenPacketViewerCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenPacketViewerCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        public static string OpenPacketViewerCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenPacketViewerCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Velocity {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Velocity", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Altitude {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Altitude", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Compass {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Compass", resourceCulture);
            }
        }
        
        public static string AltitudeIndicatorStyles_ToolTip_Vibration {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Vibration", resourceCulture);
            }
        }
    }
}
