//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string AltitudeIndicatorStyles_ToolTip_Altitude {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string AltitudeIndicatorStyles_ToolTip_Compass {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string AltitudeIndicatorStyles_ToolTip_Velocity {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        public static string AltitudeIndicatorStyles_ToolTip_Vibration {
            get {
                return ResourceManager.GetString("AltitudeIndicatorStyles_ToolTip_Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that download an element by burst.
        /// </summary>
        public static string BurstDownloadItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("BurstDownloadItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst-Download.
        /// </summary>
        public static string BurstDownloadItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("BurstDownloadItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that checks a cyclic redundancy of a file (crc32).
        /// </summary>
        public static string CalculateCrc32Command_CommandInfo_Description {
            get {
                return ResourceManager.GetString("CalculateCrc32Command_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate CRC32.
        /// </summary>
        public static string CalculateCrc32Command_CommandInfo_Name {
            get {
                return ResourceManager.GetString("CalculateCrc32Command_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that changes frame type.
        /// </summary>
        public static string ChangeFrameTypeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ChangeFrameTypeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change frame type.
        /// </summary>
        public static string ChangeFrameTypeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ChangeFrameTypeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that clears all packets.
        /// </summary>
        public static string ClearAllPacketsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ClearAllPacketsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all packets.
        /// </summary>
        public static string ClearAllPacketsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ClearAllPacketsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that creates a folder.
        /// </summary>
        public static string CreateDirectoryCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("CreateDirectoryCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a folder.
        /// </summary>
        public static string CreateDirectoryCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("CreateDirectoryCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that downloads remote entries.
        /// </summary>
        public static string DownloadItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("DownloadItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("DownloadItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that exports packets to a CSV file.
        /// </summary>
        public static string ExportPacketsToCsvCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ExportPacketsToCsvCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export packets to CSV.
        /// </summary>
        public static string ExportPacketsToCsvCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ExportPacketsToCsvCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to the device&apos;s FTP service....
        /// </summary>
        public static string FileBrowserView_AwaitingScreen_Description {
            get {
                return ResourceManager.GetString("FileBrowserView_AwaitingScreen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string FileBrowserView_AwaitingScreen_Header {
            get {
                return ResourceManager.GetString("FileBrowserView_AwaitingScreen_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst download.
        /// </summary>
        public static string FileBrowserView_Button_BurstDownload_Content {
            get {
                return ResourceManager.GetString("FileBrowserView_Button_BurstDownload_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FileBrowserView_Button_Download_Content {
            get {
                return ResourceManager.GetString("FileBrowserView_Button_Download_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Search.
        /// </summary>
        public static string FileBrowserView_Watermark_Local {
            get {
                return ResourceManager.GetString("FileBrowserView_Watermark_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Search.
        /// </summary>
        public static string FileBrowserView_Watermark_Remote {
            get {
                return ResourceManager.GetString("FileBrowserView_Watermark_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FileBrowserViewModel_BurstDownloadDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FileBrowserViewModel_BurstDownloadDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burst download.
        /// </summary>
        public static string FileBrowserViewModel_BurstDownloadDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_BurstDownloadDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download file &apos;{0}&apos;?.
        /// </summary>
        public static string FileBrowserViewModel_DownloadDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_DownloadDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string FileBrowserViewModel_DownloadDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_DownloadDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File downloaded successfully: {0}.
        /// </summary>
        public static string FileBrowserViewModel_FileDownloadedSuccessfully {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_FileDownloadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the item?.
        /// </summary>
        public static string FileBrowserViewModel_RemoveDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RemoveDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string FileBrowserViewModel_RemoveDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RemoveDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input new name.
        /// </summary>
        public static string FileBrowserViewModel_RenameDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string FileBrowserViewModel_RenameDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FileBrowserViewModel_RenameDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string FileBrowserViewModel_RenameDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_RenameDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string FileBrowserViewModel_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload file &apos;{0}&apos; to device?.
        /// </summary>
        public static string FileBrowserViewModel_UploadingDialog_Message {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_UploadingDialog_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string FileBrowserViewModel_UploadingDialog_Title {
            get {
                return ResourceManager.GetString("FileBrowserViewModel_UploadingDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that finds a file selected in a remote tree in a local tree.
        /// </summary>
        public static string FindFileOnLocalCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("FindFileOnLocalCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find file.
        /// </summary>
        public static string FindFileOnLocalCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("FindFileOnLocalCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string FlightPageViewModel_Title {
            get {
                return ResourceManager.GetString("FlightPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D position Fix.
        /// </summary>
        public static string GpsFixType_GpsFixType2dFix {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixType2dFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D position Fix.
        /// </summary>
        public static string GpsFixType_GpsFixType3dFix {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixType3dFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGPS/SBAS.
        /// </summary>
        public static string GpsFixType_GpsFixTypeDgps {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeDgps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GPS connected.
        /// </summary>
        public static string GpsFixType_GpsFixTypeNoGps {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeNoGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPP 3D position.
        /// </summary>
        public static string GpsFixType_GpsFixTypePpp {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypePpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rtk Fixed.
        /// </summary>
        public static string GpsFixType_GpsFixTypeRtkFixed {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeRtkFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTK Float.
        /// </summary>
        public static string GpsFixType_GpsFixTypeRtkFloat {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeRtkFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Fix.
        /// </summary>
        public static string GpsFixType_GpsFixTypeStatic {
            get {
                return ResourceManager.GetString("GpsFixType_GpsFixTypeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit mavlink device parameters.
        /// </summary>
        public static string HomePageParamsDeviceItemAction_ActionViewModel_Description {
            get {
                return ResourceManager.GetString("HomePageParamsDeviceItemAction_ActionViewModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params editor.
        /// </summary>
        public static string HomePageParamsDeviceItemAction_ActionViewModel_Header {
            get {
                return ResourceManager.GetString("HomePageParamsDeviceItemAction_ActionViewModel_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the device....
        /// </summary>
        public static string MavParamsPageView_AwaitingScreen_Description {
            get {
                return ResourceManager.GetString("MavParamsPageView_AwaitingScreen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string MavParamsPageView_AwaitingScreen_Header {
            get {
                return ResourceManager.GetString("MavParamsPageView_AwaitingScreen_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MavParamsPageView_CancelButton_Content {
            get {
                return ResourceManager.GetString("MavParamsPageView_CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string MavParamsPageView_Loading_Text {
            get {
                return ResourceManager.GetString("MavParamsPageView_Loading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string MavParamsPageViewModel_DeviceName_Unknown {
            get {
                return ResourceManager.GetString("MavParamsPageViewModel_DeviceName_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params.
        /// </summary>
        public static string MavParamsPageViewModel_Title {
            get {
                return ResourceManager.GetString("MavParamsPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Mission.
        /// </summary>
        public static string MissionProgressView_DownloadButton_Text {
            get {
                return ResourceManager.GetString("MissionProgressView_DownloadButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading mission.
        /// </summary>
        public static string MissionProgressView_DownLoadingMission {
            get {
                return ResourceManager.GetString("MissionProgressView_DownLoadingMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MissionProgressView_HomeDistance {
            get {
                return ResourceManager.GetString("MissionProgressView_HomeDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string MissionProgressView_MissionDistanceRTT {
            get {
                return ResourceManager.GetString("MissionProgressView_MissionDistanceRTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh mission.
        /// </summary>
        public static string MissionProgressView_RefreshButton_Text {
            get {
                return ResourceManager.GetString("MissionProgressView_RefreshButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before complete.
        /// </summary>
        public static string MissionProgressView_SubStatusText {
            get {
                return ResourceManager.GetString("MissionProgressView_SubStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string MissionProgressView_TargetDistance {
            get {
                return ResourceManager.GetString("MissionProgressView_TargetDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission progress.
        /// </summary>
        public static string MissionProgressView_Title {
            get {
                return ResourceManager.GetString("MissionProgressView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string MissionProgressView_TotalDistanceRTT {
            get {
                return ResourceManager.GetString("MissionProgressView_TotalDistanceRTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MissionProgressViewModel_MissionFlightTime_Symbol {
            get {
                return ResourceManager.GetString("MissionProgressViewModel_MissionFlightTime_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor.
        /// </summary>
        public static string MotorItemView_Label_MotorId {
            get {
                return ResourceManager.GetString("MotorItemView_Label_MotorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM.
        /// </summary>
        public static string MotorItemView_MonitoringLabel_Pwm {
            get {
                return ResourceManager.GetString("MotorItemView_MonitoringLabel_Pwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo.
        /// </summary>
        public static string MotorItemView_MonitoringLabel_Servo {
            get {
                return ResourceManager.GetString("MotorItemView_MonitoringLabel_Servo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START/STOP.
        /// </summary>
        public static string MotorItemView_ToolTip_StartStop {
            get {
                return ResourceManager.GetString("MotorItemView_ToolTip_StartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NotANumber {
            get {
                return ResourceManager.GetString("NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that opens file browser.
        /// </summary>
        public static string OpenFileBrowserCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenFileBrowserCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file browser.
        /// </summary>
        public static string OpenFileBrowserCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenFileBrowserCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that opens flight mode page.
        /// </summary>
        public static string OpenFlightModeCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenFlightModeCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open flight mode.
        /// </summary>
        public static string OpenFlightModeCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenFlightModeCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command opens mavlink params editor.
        /// </summary>
        public static string OpenMavParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenMavParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open mavlink params.
        /// </summary>
        public static string OpenMavParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenMavParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that opens packet viewer.
        /// </summary>
        public static string OpenPacketViewerCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenPacketViewerCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open packet viewer.
        /// </summary>
        public static string OpenPacketViewerCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenPacketViewerCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that opens setup page for the drone.
        /// </summary>
        public static string OpenSetupCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("OpenSetupCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Setup page.
        /// </summary>
        public static string OpenSetupCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("OpenSetupCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string PacketMessageViewModel_CsvColumn_Date {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string PacketMessageViewModel_CsvColumn_Message {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string PacketMessageViewModel_CsvColumn_Source {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string PacketMessageViewModel_CsvColumn_Type {
            get {
                return ResourceManager.GetString("PacketMessageViewModel_CsvColumn_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string PacketViewerView_ExpanderFilterBySources_Header {
            get {
                return ResourceManager.GetString("PacketViewerView_ExpanderFilterBySources_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string PacketViewerView_ExpanderFilterByTypes_Header {
            get {
                return ResourceManager.GetString("PacketViewerView_ExpanderFilterByTypes_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string PacketViewerView_Filters_CheckAll {
            get {
                return ResourceManager.GetString("PacketViewerView_Filters_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string PacketViewerView_ToolTip_ClearAll {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY/PAUSE.
        /// </summary>
        public static string PacketViewerView_ToolTip_PlayPause {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_PlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string PacketViewerView_ToolTip_Save {
            get {
                return ResourceManager.GetString("PacketViewerView_ToolTip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PacketViewerViewModel_SavePacketMessagesDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string PacketViewerViewModel_SavePacketMessagesDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Separator:.
        /// </summary>
        public static string PacketViewerViewModel_SavePacketMessagesDialog_Title {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SavePacketMessagesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet Viewer.
        /// </summary>
        public static string PacketViewerViewModel_Title {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all pinned parameters.
        /// </summary>
        public static string ParametersEditorPageView_PinsOffButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_PinsOffButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star this parameter.
        /// </summary>
        public static string ParametersEditorPageView_StarButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only starred parameters.
        /// </summary>
        public static string ParametersEditorPageView_StarsToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarsToggleButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all parameters.
        /// </summary>
        public static string ParametersEditorPageView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ParametersEditorPageViewModel_Search {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string ParametersEditorPageViewModel_Total {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/ off pin for this parameter.
        /// </summary>
        public static string ParametersEditorParameterView_PinToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_PinToggleButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot required.
        /// </summary>
        public static string ParametersEditorParameterView_RebootRequired {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_RebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ParametersEditorParameterView_UpdateButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update this parameter from UAV.
        /// </summary>
        public static string ParametersEditorParameterView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string ParametersEditorParameterView_WriteButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write this parameter to UAV.
        /// </summary>
        public static string ParametersEditorParameterView_WriteButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes. Do you want to save them?.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_Content {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential data loss warning.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_Title {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that updates param from the mavlink device.
        /// </summary>
        public static string ReadParamCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("ReadParamCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update param.
        /// </summary>
        public static string ReadParamCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("ReadParamCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that removes item.
        /// </summary>
        public static string RemoveItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RemoveItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove item.
        /// </summary>
        public static string RemoveItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RemoveItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that commits an item renaming.
        /// </summary>
        public static string RenameItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("RenameItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit item rename.
        /// </summary>
        public static string RenameItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("RenameItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB.
        /// </summary>
        public static string SavePacketMessagesDialogView_Separator_Tab {
            get {
                return ResourceManager.GetString("SavePacketMessagesDialogView_Separator_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take off.
        /// </summary>
        public static string SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_PrimaryButton_TakeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel {
            get {
                return ResourceManager.GetString("SetAltitudeDialogViewModel_ApplyDialog_SecondaryButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string SetupFrameTypeView_ApplyFrame {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_ApplyFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current frame.
        /// </summary>
        public static string SetupFrameTypeView_CurrentFrame {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_CurrentFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SetupFrameTypeView_CurrentFrame_Meta {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_CurrentFrame_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh current frame.
        /// </summary>
        public static string SetupFrameTypeView_CurrentFrame_Refresh {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_CurrentFrame_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string SetupFrameTypeView_FrameMetadata {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_FrameMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string SetupFrameTypeView_Loader_Description {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_Loader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string SetupFrameTypeView_Loader_Header {
            get {
                return ResourceManager.GetString("SetupFrameTypeView_Loader_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change frame type?.
        /// </summary>
        public static string SetupFrameTypeViewModel_ApplyConfirmation_Message {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_ApplyConfirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change frame type.
        /// </summary>
        public static string SetupFrameTypeViewModel_ApplyConfirmation_Title {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_ApplyConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SetupFrameTypeViewModel_CurrentFrame_Unknown {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_CurrentFrame_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame type.
        /// </summary>
        public static string SetupFrameTypeViewModel_Name {
            get {
                return ResourceManager.GetString("SetupFrameTypeViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string SetupMotorsView_DurationLabel_TimeUnit {
            get {
                return ResourceManager.GetString("SetupMotorsView_DurationLabel_TimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string SetupMotorsView_TestDuration {
            get {
                return ResourceManager.GetString("SetupMotorsView_TestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Test.
        /// </summary>
        public static string SetupMotorsViewModel_Name {
            get {
                return ResourceManager.GetString("SetupMotorsViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string SetupPageViewModel_Title {
            get {
                return ResourceManager.GetString("SetupPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to stop receiving parameters from the mavlink device.
        /// </summary>
        public static string StopUpdateParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("StopUpdateParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop refreshing params.
        /// </summary>
        public static string StopUpdateParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("StopUpdateParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set an Auto mode. Use it to continue mission after interrupt.
        /// </summary>
        public static string UavAction_AutoMode_Description {
            get {
                return ResourceManager.GetString("UavAction_AutoMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto mode.
        /// </summary>
        public static string UavAction_AutoMode_Name {
            get {
                return ResourceManager.GetString("UavAction_AutoMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guided mode.
        /// </summary>
        public static string UavAction_GuidedMode {
            get {
                return ResourceManager.GetString("UavAction_GuidedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a Guided mode.
        /// </summary>
        public static string UavAction_GuidedMode_Description {
            get {
                return ResourceManager.GetString("UavAction_GuidedMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string UavAction_Land {
            get {
                return ResourceManager.GetString("UavAction_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately Land.
        /// </summary>
        public static string UavAction_Land_Description {
            get {
                return ResourceManager.GetString("UavAction_Land_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to launch.
        /// </summary>
        public static string UavAction_Rtl_Description {
            get {
                return ResourceManager.GetString("UavAction_Rtl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL.
        /// </summary>
        public static string UavAction_Rtl_Name {
            get {
                return ResourceManager.GetString("UavAction_Rtl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mission.
        /// </summary>
        public static string UavAction_StartMission {
            get {
                return ResourceManager.GetString("UavAction_StartMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins uploaded mission.
        /// </summary>
        public static string UavAction_StartMission_Description {
            get {
                return ResourceManager.GetString("UavAction_StartMission_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TakeOff.
        /// </summary>
        public static string UavAction_TakeOff {
            get {
                return ResourceManager.GetString("UavAction_TakeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start takeoff.
        /// </summary>
        public static string UavAction_TakeOff_Description {
            get {
                return ResourceManager.GetString("UavAction_TakeOff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string UavRttItem_Altitude {
            get {
                return ResourceManager.GetString("UavRttItem_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azimuth.
        /// </summary>
        public static string UavRttItem_Azimuth {
            get {
                return ResourceManager.GetString("UavRttItem_Azimuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string UavRttItem_Battery {
            get {
                return ResourceManager.GetString("UavRttItem_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNSS.
        /// </summary>
        public static string UavRttItem_GNSS {
            get {
                return ResourceManager.GetString("UavRttItem_GNSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string UavRttItem_Link {
            get {
                return ResourceManager.GetString("UavRttItem_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string UavRttItem_Mode {
            get {
                return ResourceManager.GetString("UavRttItem_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string UavRttItem_Velocity {
            get {
                return ResourceManager.GetString("UavRttItem_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Altitude.
        /// </summary>
        public static string UavWidgetViewModel_SetAltitudeDialog_Title {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_SetAltitudeDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed.
        /// </summary>
        public static string UavWidgetViewModel_StatusText_Armed {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_Armed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarmed.
        /// </summary>
        public static string UavWidgetViewModel_StatusText_DisArmed {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_DisArmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Up.
        /// </summary>
        public static string UavWidgetViewModel_StatusText_PullUp {
            get {
                return ResourceManager.GetString("UavWidgetViewModel_StatusText_PullUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        public static string Unit_Byte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Byte_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string Unit_Gigabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Gigabyte_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string Unit_Kilobyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Kilobyte_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string Unit_Megabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Megabyte_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string Unit_Terabyte_Abbreviation {
            get {
                return ResourceManager.GetString("Unit_Terabyte_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command removes all pinned items from the params page.
        /// </summary>
        public static string UnpinAllParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UnpinAllParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin all params.
        /// </summary>
        public static string UnpinAllParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UnpinAllParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that refreshes params from the mavlink device.
        /// </summary>
        public static string UpdateParamsCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UpdateParamsCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh params.
        /// </summary>
        public static string UpdateParamsCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UpdateParamsCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that uploads files to the remote device.
        /// </summary>
        public static string UploadItemCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("UploadItemCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadItemCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("UploadItemCommand_CommandInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command that writes the param to the mavlink device.
        /// </summary>
        public static string WriteParamCommand_CommandInfo_Description {
            get {
                return ResourceManager.GetString("WriteParamCommand_CommandInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write param.
        /// </summary>
        public static string WritePatamCommand_CommandInfo_Name {
            get {
                return ResourceManager.GetString("WritePatamCommand_CommandInfo_Name", resourceCulture);
            }
        }
    }
}
