//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Uav {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Uav.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rate at which the HEARTBEAT message must be transmitted to announce the existence of the system on the MAVLink network.
        /// </summary>
        public static string ConnectionsIdentificationView_HeartbeatRate_Description {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatRate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat rate.
        /// </summary>
        public static string ConnectionsIdentificationView_HeartbeatRate_Header {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatRate_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After that timeout of Heartbeat packet deviceService will be removed from deviceService list.
        /// </summary>
        public static string ConnectionsIdentificationView_HeartbeatTimeout_Description {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatTimeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat timeout.
        /// </summary>
        public static string ConnectionsIdentificationView_HeartbeatTimeout_Header {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatTimeout_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each system has a network-unique system id, and each component has a system-unique component id that can be used for addressing/routing.
        /// </summary>
        public static string ConnectionsIdentificationView_SystemComponentId_Description {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_SystemComponentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System \ Component ID.
        /// </summary>
        public static string ConnectionsIdentificationView_SystemComponentId_Header {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_SystemComponentId_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout must be from {0} to {1}.
        /// </summary>
        public static string ConnectionsIdentificationViewModel_DeviceTimeout {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationViewModel_DeviceTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        public static string ConnectionsIdentificationViewModel_ToString {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationViewModel_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Serial.
        /// </summary>
        public static string ConnectionsPortsView_AddSerialCommand_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_AddSerialCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add TCP.
        /// </summary>
        public static string ConnectionsPortsView_AddTcpCommand_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_AddTcpCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add UDP.
        /// </summary>
        public static string ConnectionsPortsView_AddUdpCommand_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_AddUdpCommand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of entry that allows it to communicate with other devices in Mavlink network..
        /// </summary>
        public static string ConnectionsPortsView_Header_Description {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections ports.
        /// </summary>
        public static string ConnectionsPortsView_Header_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConnectionsShellMenuItem_Name {
            get {
                return ResourceManager.GetString("ConnectionsShellMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page allows you to configure the basic settings on the Mavlink network.
        /// </summary>
        public static string ConnectionsView_Header_Description {
            get {
                return ResourceManager.GetString("ConnectionsView_Header_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mavlink network.
        /// </summary>
        public static string ConnectionsView_Header_Title {
            get {
                return ResourceManager.GetString("ConnectionsView_Header_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ConnectionsViewModel_AddDialogPort_Add {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddDialogPort_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConnectionsViewModel_AddDialogPort_Cancel {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddDialogPort_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Mavlink serial port.
        /// </summary>
        public static string ConnectionsViewModel_AddSerialPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddSerialPortDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Mavlink TCP port.
        /// </summary>
        public static string ConnectionsViewModel_AddTcpPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddTcpPortDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new Mavlink UDP port.
        /// </summary>
        public static string ConnectionsViewModel_AddUdpPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddUdpPortDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section you can see all found devices on the network.
        /// </summary>
        public static string DeviceBrowserView_Description {
            get {
                return ResourceManager.GetString("DeviceBrowserView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device list.
        /// </summary>
        public static string DeviceBrowserView_Header {
            get {
                return ResourceManager.GetString("DeviceBrowserView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom mode.
        /// </summary>
        public static string MavlinkDeviceView_Mode_Name {
            get {
                return ResourceManager.GetString("MavlinkDeviceView_Mode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat rate.
        /// </summary>
        public static string MavlinkDeviceView_Rate_Name {
            get {
                return ResourceManager.GetString("MavlinkDeviceView_Rate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System status.
        /// </summary>
        public static string MavlinkDeviceView_Status_Name {
            get {
                return ResourceManager.GetString("MavlinkDeviceView_Status_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string PortView_ToggleButton_Disabled {
            get {
                return ResourceManager.GetString("PortView_ToggleButton_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string PortView_ToggleButton_Enabled {
            get {
                return ResourceManager.GetString("PortView_ToggleButton_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string PortViewModel_SkippedUnitTest {
            get {
                return ResourceManager.GetString("PortViewModel_SkippedUnitTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        public static string SerialPortView_BaudRate {
            get {
                return ResourceManager.GetString("SerialPortView_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port name.
        /// </summary>
        public static string SerialPortView_PortName {
            get {
                return ResourceManager.GetString("SerialPortView_PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port title.
        /// </summary>
        public static string SerialPortView_Title {
            get {
                return ResourceManager.GetString("SerialPortView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate must be value from {0} to {1}.
        /// </summary>
        public static string SerialPortViewModel_SerialPortViewModel_BaudRateValid {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_BaudRateValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New serial {0}.
        /// </summary>
        public static string SerialPortViewModel_SerialPortViewModel_NewSerial {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_NewSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a valid serial port name.
        /// </summary>
        public static string SerialPortViewModel_SerialPortViewModel_ValidSerialPort {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_ValidSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a valid name.
        /// </summary>
        public static string SerialPortViewModel_SerialPortViewModel_You_must_specify_a_valid_name {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_You_must_specify_a_valid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port title.
        /// </summary>
        public static string TcpPortView_PortTitle {
            get {
                return ResourceManager.GetString("TcpPortView_PortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        public static string TcpPortView_TcpIpAddress {
            get {
                return ResourceManager.GetString("TcpPortView_TcpIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number.
        /// </summary>
        public static string TcpPortView_TcpIpPort {
            get {
                return ResourceManager.GetString("TcpPortView_TcpIpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string UdpPortView_LocalIpAddress {
            get {
                return ResourceManager.GetString("UdpPortView_LocalIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string UdpPortView_LocalPortName {
            get {
                return ResourceManager.GetString("UdpPortView_LocalPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string UdpPortView_PortTitle {
            get {
                return ResourceManager.GetString("UdpPortView_PortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote IP Address.
        /// </summary>
        public static string UdpPortView_RemoteIpAddress {
            get {
                return ResourceManager.GetString("UdpPortView_RemoteIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote port number.
        /// </summary>
        public static string UdpPortView_RemotePortName {
            get {
                return ResourceManager.GetString("UdpPortView_RemotePortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify remote host.
        /// </summary>
        public static string UdpPortView_ToggleName {
            get {
                return ResourceManager.GetString("UdpPortView_ToggleName", resourceCulture);
            }
        }
    }
}
