//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Uav {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Uav.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration and clipping of UAV.
        /// </summary>
        public static string AltitudeIndicator_Vibration_ToolTip {
            get {
                return ResourceManager.GetString("AltitudeIndicator_Vibration_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string AttitudeIndicator_Altitude_ToolTip {
            get {
                return ResourceManager.GetString("AttitudeIndicator_Altitude_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string AttitudeIndicator_Compass_ToolTip {
            get {
                return ResourceManager.GetString("AttitudeIndicator_Compass_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string AttitudeIndicator_Velocity_ToolTip {
            get {
                return ResourceManager.GetString("AttitudeIndicator_Velocity_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed.
        /// </summary>
        public static string AttitudeViewModel_Vehicle_UpdateStatusText_Armed {
            get {
                return ResourceManager.GetString("AttitudeViewModel_Vehicle_UpdateStatusText_Armed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarmed.
        /// </summary>
        public static string AttitudeViewModel_Vehicle_UpdateStatusText_Disarmed {
            get {
                return ResourceManager.GetString("AttitudeViewModel_Vehicle_UpdateStatusText_Disarmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery level.
        /// </summary>
        public static string BatteryUavRttView_ToolTip {
            get {
                return ResourceManager.GetString("BatteryUavRttView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can reload controller.
        /// </summary>
        public static string ControllerReloadQuickParamView_Description {
            get {
                return ResourceManager.GetString("ControllerReloadQuickParamView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller reload.
        /// </summary>
        public static string ControllerReloadQuickParamView_Header {
            get {
                return ResourceManager.GetString("ControllerReloadQuickParamView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ControllerReloadQuickParamView_ReloadButton_Content {
            get {
                return ResourceManager.GetString("ControllerReloadQuickParamView_ReloadButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU load of UAV.
        /// </summary>
        public static string CpuLoadUavRttView_ToolTip {
            get {
                return ResourceManager.GetString("CpuLoadUavRttView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAV current.
        /// </summary>
        public static string CurrentUavRttView_ToolTip {
            get {
                return ResourceManager.GetString("CurrentUavRttView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can change FailSafe parameters.
        /// </summary>
        public static string FailSafeQuickParamView_Description {
            get {
                return ResourceManager.GetString("FailSafeQuickParamView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FailSafe parameters.
        /// </summary>
        public static string FailSafeQuickParamView_Header {
            get {
                return ResourceManager.GetString("FailSafeQuickParamView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAV time in flight.
        /// </summary>
        public static string FlightTimeUavRttView_ToolTip {
            get {
                return ResourceManager.GetString("FlightTimeUavRttView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find UAV.
        /// </summary>
        public static string FlightUavView_FindButton_ToolTip {
            get {
                return ResourceManager.GetString("FlightUavView_FindButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow/Unfollow UAV.
        /// </summary>
        public static string FlightUavView_FollowButton_ToolTip {
            get {
                return ResourceManager.GetString("FlightUavView_FollowButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize/Maximize UAV.
        /// </summary>
        public static string FlightUavView_Minimize_ToolTip {
            get {
                return ResourceManager.GetString("FlightUavView_Minimize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to this UAV on map.
        /// </summary>
        public static string FlightUavView_MoveToButton_ToolTip {
            get {
                return ResourceManager.GetString("FlightUavView_MoveToButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uav actions.
        /// </summary>
        public static string FlightUavView_UavDropDownControls_Title {
            get {
                return ResourceManager.GetString("FlightUavView_UavDropDownControls_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User send GoTo &apos;{0}&apos; for {0}.
        /// </summary>
        public static string GoToMapAnchorActionViewModel_ExecuteImpl_LogInfo_Value {
            get {
                return ResourceManager.GetString("GoToMapAnchorActionViewModel_ExecuteImpl_LogInfo_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select target for GoTo action.
        /// </summary>
        public static string GoToMapAnchorActionViewModel_ExecuteImpl_ShowTargetDialog_Value {
            get {
                return ResourceManager.GetString("GoToMapAnchorActionViewModel_ExecuteImpl_ShowTargetDialog_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoTo.
        /// </summary>
        public static string GoToMapAnchorActionViewModel_Title {
            get {
                return ResourceManager.GetString("GoToMapAnchorActionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from UAV to home.
        /// </summary>
        public static string HomeDistanceUavRttView_ToolTip {
            get {
                return ResourceManager.GetString("HomeDistanceUavRttView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each system has a network-unique system id, and each component has a system-unique component id that can be used for addressing/routing.
        /// </summary>
        public static string IdentityQuickParamView_Description {
            get {
                return ResourceManager.GetString("IdentityQuickParamView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System ID.
        /// </summary>
        public static string IdentityQuickParamView_Header {
            get {
                return ResourceManager.GetString("IdentityQuickParamView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User send DoLand for {0}.
        /// </summary>
        public static string LandAnchorActionViewModel_ExecuteImpl_LogInfo {
            get {
                return ResourceManager.GetString("LandAnchorActionViewModel_ExecuteImpl_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediately land.
        /// </summary>
        public static string LandAnchorActionViewModel_Title {
            get {
                return ResourceManager.GetString("LandAnchorActionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAV link quality.
        /// </summary>
        public static string LinkQualityUavRttView_ToolTip {
            get {
                return ResourceManager.GetString("LinkQualityUavRttView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables mission trajectory and waypoints visibility.
        /// </summary>
        public static string MissionStatusView_DisableLayersButton_ToolTip {
            get {
                return ResourceManager.GetString("MissionStatusView_DisableLayersButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load mission from UAV.
        /// </summary>
        public static string MissionStatusView_GetMissionButton_ToolTip {
            get {
                return ResourceManager.GetString("MissionStatusView_GetMissionButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission: {0}.
        /// </summary>
        public static string MissionStatusView_MissionDistance {
            get {
                return ResourceManager.GetString("MissionStatusView_MissionDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mission progress.
        /// </summary>
        public static string MissionStatusView_MissionProgress_ToolTip {
            get {
                return ResourceManager.GetString("MissionStatusView_MissionProgress_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/off mission trajectory visibility.
        /// </summary>
        public static string MissionStatusView_TogglePolygonButton_ToolTip {
            get {
                return ResourceManager.GetString("MissionStatusView_TogglePolygonButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/off mission way points visibility.
        /// </summary>
        public static string MissionStatusView_ToggleWaypointsButton_ToolTip {
            get {
                return ResourceManager.GetString("MissionStatusView_ToggleWaypointsButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string MissionStatusView_TotalDistance {
            get {
                return ResourceManager.GetString("MissionStatusView_TotalDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mission.
        /// </summary>
        public static string PlaningMissionViewModel_InternalAfterMapInit_Vehicle_Name_Subscribe {
            get {
                return ResourceManager.GetString("PlaningMissionViewModel_InternalAfterMapInit_Vehicle_Name_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear mission error {0}.
        /// </summary>
        public static string PlaningMissionViewModel_OnClearError_LogInfo {
            get {
                return ResourceManager.GetString("PlaningMissionViewModel_OnClearError_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download mission error {0}.
        /// </summary>
        public static string PlaningMissionViewModel_OnDownloadError_LogInfo {
            get {
                return ResourceManager.GetString("PlaningMissionViewModel_OnDownloadError_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload mission error {0}.
        /// </summary>
        public static string PlaningMissionViewModel_OnUploadError_LogInfo {
            get {
                return ResourceManager.GetString("PlaningMissionViewModel_OnUploadError_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced setup.
        /// </summary>
        public static string QuickParamsSetupPageView_AdvancedSetupButton_Text {
            get {
                return ResourceManager.GetString("QuickParamsSetupPageView_AdvancedSetupButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read all.
        /// </summary>
        public static string QuickParamsSetupPageView_ReadAllButton_Text {
            get {
                return ResourceManager.GetString("QuickParamsSetupPageView_ReadAllButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write all.
        /// </summary>
        public static string QuickParamsSetupPageView_WriteAllButton_Text {
            get {
                return ResourceManager.GetString("QuickParamsSetupPageView_WriteAllButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must click the write button if you want to save and apply the changes..
        /// </summary>
        public static string QuickParamsSetupPageView_WriteRequired_Message {
            get {
                return ResourceManager.GetString("QuickParamsSetupPageView_WriteRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write required.
        /// </summary>
        public static string QuickParamsSetupPageView_WriteRequired_Title {
            get {
                return ResourceManager.GetString("QuickParamsSetupPageView_WriteRequired_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string RebootAutopilotAnchorActionViewModel_DialogPrimaryButton {
            get {
                return ResourceManager.GetString("RebootAutopilotAnchorActionViewModel_DialogPrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RebootAutopilotAnchorActionViewModel_DialogSecondaryButton {
            get {
                return ResourceManager.GetString("RebootAutopilotAnchorActionViewModel_DialogSecondaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User sent Reboot Autopilot command with {0} and {1}.
        /// </summary>
        public static string RebootAutopilotAnchorActionViewModel_LogMessage {
            get {
                return ResourceManager.GetString("RebootAutopilotAnchorActionViewModel_LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot/Shutdown Autopilot.
        /// </summary>
        public static string RebootAutopilotAnchorActionViewModel_Title {
            get {
                return ResourceManager.GetString("RebootAutopilotAnchorActionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Autopilot reboot/shutdown mode.
        /// </summary>
        public static string RebootAutopilotView_AutopilotReboot_Description {
            get {
                return ResourceManager.GetString("RebootAutopilotView_AutopilotReboot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose companion reboot/shutdown mode.
        /// </summary>
        public static string RebootAutopilotView_CompanionReboot_Description {
            get {
                return ResourceManager.GetString("RebootAutopilotView_CompanionReboot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI of.
        /// </summary>
        public static string RoiAnchor_Vehicle_Name {
            get {
                return ResourceManager.GetString("RoiAnchor_Vehicle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaw angle.
        /// </summary>
        public static string RoiAnchor_Vehicle_Yaw_Sample_Description {
            get {
                return ResourceManager.GetString("RoiAnchor_Vehicle_Yaw_Sample_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deg.
        /// </summary>
        public static string RoiAnchor_Vehicle_Yaw_Sample_Unit {
            get {
                return ResourceManager.GetString("RoiAnchor_Vehicle_Yaw_Sample_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User set ROI &apos;{0}&apos; for {1}.
        /// </summary>
        public static string RoiAnchorActionViewModel_ExecuteImpl_LogInfo {
            get {
                return ResourceManager.GetString("RoiAnchorActionViewModel_ExecuteImpl_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select target for region of interests (ROI).
        /// </summary>
        public static string RoiAnchorActionViewModel_ExecuteImpl_ShowTargetDialog_Value {
            get {
                return ResourceManager.GetString("RoiAnchorActionViewModel_ExecuteImpl_ShowTargetDialog_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set ROI.
        /// </summary>
        public static string RoiAnchorActionViewModel_Title {
            get {
                return ResourceManager.GetString("RoiAnchorActionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User send Return To the Launch(RTL) for {0}.
        /// </summary>
        public static string RtlAnchorActionViewModel_ExecuteImpl_LogInfo {
            get {
                return ResourceManager.GetString("RtlAnchorActionViewModel_ExecuteImpl_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to launch (RTL).
        /// </summary>
        public static string RtlAnchorActionViewModel_RTL {
            get {
                return ResourceManager.GetString("RtlAnchorActionViewModel_RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change UAV mode from list.
        /// </summary>
        public static string SelectModeAnchorActionView_DialogDescription {
            get {
                return ResourceManager.GetString("SelectModeAnchorActionView_DialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string SelectModeAnchorActionViewModel_DialogPrimaryButton {
            get {
                return ResourceManager.GetString("SelectModeAnchorActionViewModel_DialogPrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SelectModeAnchorActionViewModel_DialogSecondaryButton {
            get {
                return ResourceManager.GetString("SelectModeAnchorActionViewModel_DialogSecondaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User sent SetVehicleMode from {0} to {1}.
        /// </summary>
        public static string SelectModeAnchorActionViewModel_LogMessage {
            get {
                return ResourceManager.GetString("SelectModeAnchorActionViewModel_LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select UAV mode.
        /// </summary>
        public static string SelectModeAnchorActionViewModel_Title {
            get {
                return ResourceManager.GetString("SelectModeAnchorActionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can change the speeds.
        /// </summary>
        public static string SpeedsQuickParamView_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeds.
        /// </summary>
        public static string SpeedsQuickParamView_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude during Landing at which vehicle slows to LAND_SPEED. Increment - 0.1. Range 1-100. [{0:F2} cm] [{1:F2} ft]. Note: This parameter is for advanced users..
        /// </summary>
        public static string SpeedsQuickParamView_LAND_ALT_LOW_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_ALT_LOW_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land altitude low (LAND_ALT_LOW).
        /// </summary>
        public static string SpeedsQuickParamView_LAND_ALT_LOW_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_ALT_LOW_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string SpeedsQuickParamView_LAND_ALT_LOW_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_ALT_LOW_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descent speed for the final stage of landing in cm/s. Increment - 0.1. Range 0.3-2. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_LAND_SPEED_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_SPEED_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land speed (LAND_SPEED).
        /// </summary>
        public static string SpeedsQuickParamView_LAND_SPEED_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_SPEED_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The descent speed for the first stage of landing in cm/s. If this is zero then WPNAV_SPEED_DN is used. Increment - 0.1. Range 0-5. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_LAND_SPEED_HIGH_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_SPEED_HIGH_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land speed high (LAND_SPEED_HIGH).
        /// </summary>
        public static string SpeedsQuickParamView_LAND_SPEED_HIGH_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_SPEED_HIGH_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_LAND_SPEED_HIGH_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_SPEED_HIGH_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_LAND_SPEED_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LAND_SPEED_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the maximum speed in cm/s which the aircraft will travel horizontally while in loiter mode. Increment - 0.5. Range 0.2-35. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_LOIT_SPEED_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LOIT_SPEED_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loiter Horizontal Maximum Speed (LOIT_SPEED).
        /// </summary>
        public static string SpeedsQuickParamView_LOIT_SPEED_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LOIT_SPEED_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_LOIT_SPEED_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_LOIT_SPEED_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum vertical descending velocity the pilot may request in cm/s. If 0 PILOT_SPEED_UP value is used. Increment - 0.1. Range 0-5. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_PILOT_SPEED_DN_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_PILOT_SPEED_DN_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot maximum vertical speed descending (PILOT_SPEED_DN).
        /// </summary>
        public static string SpeedsQuickParamView_PILOT_SPEED_DN_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_PILOT_SPEED_DN_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_PILOT_SPEED_DN_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_PILOT_SPEED_DN_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum vertical ascending velocity the pilot may request in cm/s. Increment - 0.1. Range 0.5-5. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_PILOT_SPEED_UP_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_PILOT_SPEED_UP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pilot maximum vertical speed ascending (PILOT_SPEED_UP).
        /// </summary>
        public static string SpeedsQuickParamView_PILOT_SPEED_UP_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_PILOT_SPEED_UP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_PILOT_SPEED_UP_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_PILOT_SPEED_UP_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the speed in cm/s which the aircraft will attempt to maintain horizontally while flying home. If this is set to zero, WPNAV_SPEED will be used instead. Increment - 50. Range 0-2000. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_RTL_SPEED_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_RTL_SPEED_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL speed (RTL_SPEED).
        /// </summary>
        public static string SpeedsQuickParamView_RTL_SPEED_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_RTL_SPEED_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_RTL_SPEED_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_RTL_SPEED_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the speed in cm/s which the aircraft will attempt to maintain horizontally during a WP mission. Increment - 0.5. Range 0.2-20. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the speed in cm/s which the aircraft will attempt to maintain while descending during a WP mission. Increment - 0.1. Range 0.1-5. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_DN_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_DN_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint Descent Speed Target (WPNAV_SPEED_DN).
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_DN_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_DN_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_DN_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_DN_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint Horizontal Speed Target (WPNAV_SPEED).
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the speed in cm/s which the aircraft will attempt to maintain while climbing during a WP mission. Increment - 0.5. Range 0.1-10. [{0:F2} cm/s] [{1:F2} km/h] [{2:F2} mi/h]..
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_UP_Description {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_UP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint Climb Speed Target (WPNAV_SPEED_UP).
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_UP_Header {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_UP_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string SpeedsQuickParamView_WPNAV_SPEED_UP_Units {
            get {
                return ResourceManager.GetString("SpeedsQuickParamView_WPNAV_SPEED_UP_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User send Start mission for {0}.
        /// </summary>
        public static string StartAutoAnchorActionViewModel_ExecuteImpl_LogInfo {
            get {
                return ResourceManager.GetString("StartAutoAnchorActionViewModel_ExecuteImpl_LogInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start mission.
        /// </summary>
        public static string StartAutoAnchorActionViewModel_Title {
            get {
                return ResourceManager.GetString("StartAutoAnchorActionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set altitude above ground level (AGL) for takeoff command..
        /// </summary>
        public static string TakeOffAnchorActionViewModel_DialogDescription {
            get {
                return ResourceManager.GetString("TakeOffAnchorActionViewModel_DialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take off.
        /// </summary>
        public static string TakeOffAnchorActionViewModel_DialogPrimaryButton {
            get {
                return ResourceManager.GetString("TakeOffAnchorActionViewModel_DialogPrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TakeOffAnchorActionViewModel_DialogSecondaryButton {
            get {
                return ResourceManager.GetString("TakeOffAnchorActionViewModel_DialogSecondaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User send TakeOff at {0} altitude for {1}.
        /// </summary>
        public static string TakeOffAnchorActionViewModel_LogMessage {
            get {
                return ResourceManager.GetString("TakeOffAnchorActionViewModel_LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to arm/disarm {0}.
        /// </summary>
        public static string TakeOffAnchorActionViewModel_OnCommandError {
            get {
                return ResourceManager.GetString("TakeOffAnchorActionViewModel_OnCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take off.
        /// </summary>
        public static string TakeOffAnchorActionViewModel_Title {
            get {
                return ResourceManager.GetString("TakeOffAnchorActionViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude must be greater or equal {0}..
        /// </summary>
        public static string TakeOffAnchorActionViewModel_ValidValue {
            get {
                return ResourceManager.GetString("TakeOffAnchorActionViewModel_ValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGL Altitude: {0}.
        /// </summary>
        public static string UavAnchor_AGL_Altitude {
            get {
                return ResourceManager.GetString("UavAnchor_AGL_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNSS Altitude: {0}.
        /// </summary>
        public static string UavAnchor_GNSS_Altitude {
            get {
                return ResourceManager.GetString("UavAnchor_GNSS_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0}.
        /// </summary>
        public static string UavAnchor_Latitude {
            get {
                return ResourceManager.GetString("UavAnchor_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude: {0}.
        /// </summary>
        public static string UavAnchor_Longitude {
            get {
                return ResourceManager.GetString("UavAnchor_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N\A.
        /// </summary>
        public static string UavRttItem_ValueNotAvailable {
            get {
                return ResourceManager.GetString("UavRttItem_ValueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string VehiclesShellMenuItemProvider_ShellMenuItem_Settings {
            get {
                return ResourceManager.GetString("VehiclesShellMenuItemProvider_ShellMenuItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAV voltage.
        /// </summary>
        public static string VoltageUavRttItemView_ToolTip {
            get {
                return ResourceManager.GetString("VoltageUavRttItemView_ToolTip", resourceCulture);
            }
        }
    }
}
