//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Api.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration and clipping of UAV.
        /// </summary>
        public static string AltitudeIndicator_Vibration_ToolTip {
            get {
                return ResourceManager.GetString("AltitudeIndicator_Vibration_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string AnchorsEditorView_TextBlock_Actions {
            get {
                return ResourceManager.GetString("AnchorsEditorView_TextBlock_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string AnchorsEditorView_TextBlock_Altitude_Text {
            get {
                return ResourceManager.GetString("AnchorsEditorView_TextBlock_Altitude_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string AnchorsEditorView_TextBlock_Latitude_Text {
            get {
                return ResourceManager.GetString("AnchorsEditorView_TextBlock_Latitude_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string AnchorsEditorView_TextBlock_Longitude_Text {
            get {
                return ResourceManager.GetString("AnchorsEditorView_TextBlock_Longitude_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anchor Editor.
        /// </summary>
        public static string AnchorsEditorViewModel_Title {
            get {
                return ResourceManager.GetString("AnchorsEditorViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string AttitudeIndicator_Altitude_ToolTip {
            get {
                return ResourceManager.GetString("AttitudeIndicator_Altitude_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string AttitudeIndicator_Compass_ToolTip {
            get {
                return ResourceManager.GetString("AttitudeIndicator_Compass_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity.
        /// </summary>
        public static string AttitudeIndicator_Velocity_ToolTip {
            get {
                return ResourceManager.GetString("AttitudeIndicator_Velocity_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number.
        /// </summary>
        public static string DistanceMeasureUnit_ErrorMessage_NotANumber {
            get {
                return ResourceManager.GetString("DistanceMeasureUnit_ErrorMessage_NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string DistanceMeasureUnit_ErrorMessage_NotValid {
            get {
                return ResourceManager.GetString("DistanceMeasureUnit_ErrorMessage_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be null or white space.
        /// </summary>
        public static string DistanceMeasureUnit_ErrorMessage_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("DistanceMeasureUnit_ErrorMessage_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string HierarchicalStoreView_Button_EditFileName {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_Button_EditFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New File.
        /// </summary>
        public static string HierarchicalStoreView_Button_ToolTip_CreateNewFile {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_Button_ToolTip_CreateNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Folder.
        /// </summary>
        public static string HierarchicalStoreView_Button_ToolTip_CreateNewFolder {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_Button_ToolTip_CreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh .
        /// </summary>
        public static string HierarchicalStoreView_Button_ToolTip_Refresh {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_Button_ToolTip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string HierarchicalStoreView_File_Button_DeleteFile {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_File_Button_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move File.
        /// </summary>
        public static string HierarchicalStoreView_File_Button_MoveFile {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_File_Button_MoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Folder.
        /// </summary>
        public static string HierarchicalStoreView_Folder_Button_DeleteFolder {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_Folder_Button_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Folder.
        /// </summary>
        public static string HierarchicalStoreView_Folder_Button_EditFolderName {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_Folder_Button_EditFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Folder.
        /// </summary>
        public static string HierarchicalStoreView_Folder_Button_MoveFolderToFolder {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_Folder_Button_MoveFolderToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HierarchicalStoreView_TextBlock_Text_Cancel {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_TextBlock_Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Folder.
        /// </summary>
        public static string HierarchicalStoreView_TextBlock_Text_MoveFolder {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_TextBlock_Text_MoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Here.
        /// </summary>
        public static string HierarchicalStoreView_TextBlock_Text_MoveHere {
            get {
                return ResourceManager.GetString("HierarchicalStoreView_TextBlock_Text_MoveHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string HierarhicalStoreView_Search_Textbox_Watermark {
            get {
                return ResourceManager.GetString("HierarhicalStoreView_Search_Textbox_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move anchors.
        /// </summary>
        public static string MapMoverActionView_Title {
            get {
                return ResourceManager.GetString("MapMoverActionView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed wing.
        /// </summary>
        public static string MavlinkHelper_GetTypeName_FixedWing {
            get {
                return ResourceManager.GetString("MavlinkHelper_GetTypeName_FixedWing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        public static string MavlinkHelper_GetTypeName_Helicopter {
            get {
                return ResourceManager.GetString("MavlinkHelper_GetTypeName_Helicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexarotor.
        /// </summary>
        public static string MavlinkHelper_GetTypeName_HexaRotor {
            get {
                return ResourceManager.GetString("MavlinkHelper_GetTypeName_HexaRotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octorotor.
        /// </summary>
        public static string MavlinkHelper_GetTypeName_OctoRotor {
            get {
                return ResourceManager.GetString("MavlinkHelper_GetTypeName_OctoRotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrotor.
        /// </summary>
        public static string MavlinkHelper_GetTypeName_QuadRotor {
            get {
                return ResourceManager.GetString("MavlinkHelper_GetTypeName_QuadRotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricopter.
        /// </summary>
        public static string MavlinkHelper_GetTypeName_TriCopter {
            get {
                return ResourceManager.GetString("MavlinkHelper_GetTypeName_TriCopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type.
        /// </summary>
        public static string MavlinkHelper_GetTypeName_UnknownType {
            get {
                return ResourceManager.GetString("MavlinkHelper_GetTypeName_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number.
        /// </summary>
        public static string MeasureUnitBase_ErrorMessage_NotANumber {
            get {
                return ResourceManager.GetString("MeasureUnitBase_ErrorMessage_NotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be null or white space.
        /// </summary>
        public static string MeasureUnitBase_ErrorMessage_NullOrWhiteSpace {
            get {
                return ResourceManager.GetString("MeasureUnitBase_ErrorMessage_NullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than {0} ({1}).
        /// </summary>
        public static string MeasureUnitExtensions_ErrorMessage_GreaterValue {
            get {
                return ResourceManager.GetString("MeasureUnitExtensions_ErrorMessage_GreaterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be less than {0} ({1}).
        /// </summary>
        public static string MeasureUnitExtensions_ErrorMessage_LesserValue {
            get {
                return ResourceManager.GetString("MeasureUnitExtensions_ErrorMessage_LesserValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all pinned parameters.
        /// </summary>
        public static string ParametersEditorPageView_PinsOffButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_PinsOffButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star this parameter.
        /// </summary>
        public static string ParametersEditorPageView_StarButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only starred parameters.
        /// </summary>
        public static string ParametersEditorPageView_StarsToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_StarsToggleButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all parameters.
        /// </summary>
        public static string ParametersEditorPageView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorPageView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ParametersEditorPageViewModel_Search {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}.
        /// </summary>
        public static string ParametersEditorPageViewModel_Total {
            get {
                return ResourceManager.GetString("ParametersEditorPageViewModel_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On/off pin for this parameter.
        /// </summary>
        public static string ParametersEditorParameterView_PinToggleButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_PinToggleButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot required.
        /// </summary>
        public static string ParametersEditorParameterView_RebootRequired {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_RebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ParametersEditorParameterView_UpdateButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update this parameter from UAV.
        /// </summary>
        public static string ParametersEditorParameterView_UpdateButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_UpdateButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string ParametersEditorParameterView_WriteButton {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write this parameter to UAV.
        /// </summary>
        public static string ParametersEditorParameterView_WriteButton_ToolTip {
            get {
                return ResourceManager.GetString("ParametersEditorParameterView_WriteButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re trying to open another menu folder, but you have unsaved changes in the current one. Do you want to save them?.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_Content {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential data loss warning.
        /// </summary>
        public static string ParamPageViewModel_DataLossDialog_Title {
            get {
                return ResourceManager.GetString("ParamPageViewModel_DataLossDialog_Title", resourceCulture);
            }
        }
    }
}
