//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Core {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asv.Drones.Gui.Core.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string SettingsShellMenuProvider_SettingsShellMenuProvider_Settings {
            get {
                return ResourceManager.GetString("SettingsShellMenuProvider_SettingsShellMenuProvider_Settings", resourceCulture);
            }
        }
        
        public static string FlightShellMenuItem_Name {
            get {
                return ResourceManager.GetString("FlightShellMenuItem_Name", resourceCulture);
            }
        }
        
        public static string ThemeService_Themes_Contrast {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Contrast", resourceCulture);
            }
        }
        
        public static string ThemeService_Themes_Light {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Light", resourceCulture);
            }
        }
        
        public static string ThemeService_Themes_Dark {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Dark", resourceCulture);
            }
        }
        
        public static string ThemeService_FlowDirections_LeftToRight {
            get {
                return ResourceManager.GetString("ThemeService_FlowDirections_LeftToRight", resourceCulture);
            }
        }
        
        public static string ThemeService_FlowDirections_RightToLeft {
            get {
                return ResourceManager.GetString("ThemeService_FlowDirections_RightToLeft", resourceCulture);
            }
        }
        
        public static string SettingsThemeViewModel_CurrentTheme {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentTheme", resourceCulture);
            }
        }
        
        public static string SettingsThemeViewModel_ChangeThemeDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_ChangeThemeDescription", resourceCulture);
            }
        }
        
        public static string SettingsThemeViewModel_CurrentLanguage {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentLanguage", resourceCulture);
            }
        }
        
        public static string SettingsThemeViewModel_CurrentLanguageDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentLanguageDescription", resourceCulture);
            }
        }
        
        public static string SettingsThemeViewModel_FlowDirection {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_FlowDirection", resourceCulture);
            }
        }
        
        public static string SettingsThemeViewModel_FlowDirectionDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_FlowDirectionDescription", resourceCulture);
            }
        }
        
        public static string PlaningShellMenuItem_Name {
            get {
                return ResourceManager.GetString("PlaningShellMenuItem_Name", resourceCulture);
            }
        }
        
        public static string ByteSize_BytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_BytesUnit", resourceCulture);
            }
        }
        
        public static string ByteSize_KilobytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_KilobytesUnit", resourceCulture);
            }
        }
        
        public static string ByteSize_MegabytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_MegabytesUnit", resourceCulture);
            }
        }
        
        public static string ByteSize_GigabytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_GigabytesUnit", resourceCulture);
            }
        }
        
        public static string Common_NotAvailable {
            get {
                return ResourceManager.GetString("Common_NotAvailable", resourceCulture);
            }
        }
        
        public static string BytesRate_BytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_BytesPerSecondUnit", resourceCulture);
            }
        }
        
        public static string BytesRate_KiloBytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_KiloBytesPerSecondUnit", resourceCulture);
            }
        }
        
        public static string BytesRate_MegaBytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_MegaBytesPerSecondUnit", resourceCulture);
            }
        }
        
        public static string BytesRate_GigaBytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_GigaBytesPerSecondUnit", resourceCulture);
            }
        }
        
        public static string ItemsRate_HerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_HerzUnit", resourceCulture);
            }
        }
        
        public static string ItemsRate_KiloHerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_KiloHerzUnit", resourceCulture);
            }
        }
        
        public static string ItemsRate_MegaHerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_MegaHerzUnit", resourceCulture);
            }
        }
        
        public static string ItemsRate_GigaHerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_GigaHerzUnit", resourceCulture);
            }
        }
        
        public static string SettingsView_RebootRequiredTitle {
            get {
                return ResourceManager.GetString("SettingsView_RebootRequiredTitle", resourceCulture);
            }
        }
        
        public static string SettingsView_RebootRequiredDescription {
            get {
                return ResourceManager.GetString("SettingsView_RebootRequiredDescription", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_Distance {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_Distance", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_DistanceDescription {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_DistanceDescription", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_Altitude {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_Altitude", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_AltitudeDescription {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_AltitudeDescription", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_Latitude {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_Latitude", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_Longitude {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_Longitude", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_LatitudeLongitudeDescription {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_LatitudeLongitudeDescription", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_DistanceMeters {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_DistanceMeters", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_DistanceInternationalNauticalMiles {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_DistanceInternationalNauticalMiles", resourceCulture);
            }
        }
        
        public static string Altitude_Meter_Title {
            get {
                return ResourceManager.GetString("Altitude_Meter_Title", resourceCulture);
            }
        }
        
        public static string Altitude_Feet_Title {
            get {
                return ResourceManager.GetString("Altitude_Feet_Title", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_LatitudeLongtitudeDegrees {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_LatitudeLongtitudeDegrees", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_LatitudeLongtitudeDegreesMinutesSeconds {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_LatitudeLongtitudeDegreesMinutesSeconds", resourceCulture);
            }
        }
        
        public static string Altitude_Feet_Unit {
            get {
                return ResourceManager.GetString("Altitude_Feet_Unit", resourceCulture);
            }
        }
        
        public static string Altitude_Meter_Unit {
            get {
                return ResourceManager.GetString("Altitude_Meter_Unit", resourceCulture);
            }
        }
        
        public static string Distance_Meters_Unit {
            get {
                return ResourceManager.GetString("Distance_Meters_Unit", resourceCulture);
            }
        }
        
        public static string Distance_NauticalMiles_Unit {
            get {
                return ResourceManager.GetString("Distance_NauticalMiles_Unit", resourceCulture);
            }
        }
        
        public static string Velocity_MetersPerSecondUnit {
            get {
                return ResourceManager.GetString("Velocity_MetersPerSecondUnit", resourceCulture);
            }
        }
        
        public static string Velocity_KilometersPerHourUnit {
            get {
                return ResourceManager.GetString("Velocity_KilometersPerHourUnit", resourceCulture);
            }
        }
        
        public static string Velocity_MilesPerHourUnit {
            get {
                return ResourceManager.GetString("Velocity_MilesPerHourUnit", resourceCulture);
            }
        }
        
        public static string RelativeTime_MillisecondsUnit {
            get {
                return ResourceManager.GetString("RelativeTime_MillisecondsUnit", resourceCulture);
            }
        }
        
        public static string RelativeTime_SecondsUnit {
            get {
                return ResourceManager.GetString("RelativeTime_SecondsUnit", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_MeasurementUnits_Header_Title {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_MeasurementUnits_Header_Title", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_MeasurementUnits_Header_Description {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_MeasurementUnits_Header_Description", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_Velocity {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_Velocity", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_VelocityDescription {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_VelocityDescription", resourceCulture);
            }
        }
        
        public static string HeaderFileMenu_Header {
            get {
                return ResourceManager.GetString("HeaderFileMenu_Header", resourceCulture);
            }
        }
        
        public static string HeaderOpenMenu_Header {
            get {
                return ResourceManager.GetString("HeaderOpenMenu_Header", resourceCulture);
            }
        }
        
        public static string GlobalCommands_OpenStoreDialogTitle {
            get {
                return ResourceManager.GetString("GlobalCommands_OpenStoreDialogTitle", resourceCulture);
            }
        }
        
        public static string MapSettingsView_MapProvider_Description {
            get {
                return ResourceManager.GetString("MapSettingsView_MapProvider_Description", resourceCulture);
            }
        }
        
        public static string MapSettingsView_MapProvider_Header {
            get {
                return ResourceManager.GetString("MapSettingsView_MapProvider_Header", resourceCulture);
            }
        }
        
        public static string MapSettingsView_MapsInfo_ButtonTitle {
            get {
                return ResourceManager.GetString("MapSettingsView_MapsInfo_ButtonTitle", resourceCulture);
            }
        }
        
        public static string MapSettingsView_MapsInfo_Description {
            get {
                return ResourceManager.GetString("MapSettingsView_MapsInfo_Description", resourceCulture);
            }
        }
        
        public static string MapSettingsView_MapsInfo_Header {
            get {
                return ResourceManager.GetString("MapSettingsView_MapsInfo_Header", resourceCulture);
            }
        }
        
        public static string MapSettingsViewModel_MapDialogTitle {
            get {
                return ResourceManager.GetString("MapSettingsViewModel_MapDialogTitle", resourceCulture);
            }
        }
        
        public static string Distance_Meters_Title {
            get {
                return ResourceManager.GetString("Distance_Meters_Title", resourceCulture);
            }
        }
        
        public static string Distance_NauticalMiles_Title {
            get {
                return ResourceManager.GetString("Distance_NauticalMiles_Title", resourceCulture);
            }
        }
        
        public static string LogMessagesShellMenuItem_Name {
            get {
                return ResourceManager.GetString("LogMessagesShellMenuItem_Name", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_By {
            get {
                return ResourceManager.GetString("LogMessagesPageView_By", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_SearchWatermark {
            get {
                return ResourceManager.GetString("LogMessagesPageView_SearchWatermark", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_From {
            get {
                return ResourceManager.GetString("LogMessagesPageView_From", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_To {
            get {
                return ResourceManager.GetString("LogMessagesPageView_To", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_Filtered {
            get {
                return ResourceManager.GetString("LogMessagesPageView_Filtered", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_Total {
            get {
                return ResourceManager.GetString("LogMessagesPageView_Total", resourceCulture);
            }
        }
        
        public static string LogMessagesPageViewModel_LogName {
            get {
                return ResourceManager.GetString("LogMessagesPageViewModel_LogName", resourceCulture);
            }
        }
        
        public static string LogMessagesPageViewModel_RefreshErrorMessage {
            get {
                return ResourceManager.GetString("LogMessagesPageViewModel_RefreshErrorMessage", resourceCulture);
            }
        }
        
        public static string LogMessagesPageViewModel_ClearAllMessage {
            get {
                return ResourceManager.GetString("LogMessagesPageViewModel_ClearAllMessage", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_SerialPortViewModel_You_must_specify_a_valid_name {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_You_must_specify_a_valid_name", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_SerialPortViewModel_ValidSerialPort {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_ValidSerialPort", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_SerialPortViewModel_BaudRateValid {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_BaudRateValid", resourceCulture);
            }
        }
        
        public static string SerialPortViewModel_SerialPortViewModel_NewSerial {
            get {
                return ResourceManager.GetString("SerialPortViewModel_SerialPortViewModel_NewSerial", resourceCulture);
            }
        }
        
        public static string SerialPortView_Title {
            get {
                return ResourceManager.GetString("SerialPortView_Title", resourceCulture);
            }
        }
        
        public static string SerialPortView_PortName {
            get {
                return ResourceManager.GetString("SerialPortView_PortName", resourceCulture);
            }
        }
        
        public static string SerialPortView_BaudRate {
            get {
                return ResourceManager.GetString("SerialPortView_BaudRate", resourceCulture);
            }
        }
        
        public static string ConnectionsShellMenuItem_Name {
            get {
                return ResourceManager.GetString("ConnectionsShellMenuItem_Name", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_AddDialogPort_Add {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddDialogPort_Add", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_AddDialogPort_Cancel {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddDialogPort_Cancel", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_AddSerialPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddSerialPortDialog_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_AddTcpPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddTcpPortDialog_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_AddUdpPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_AddUdpPortDialog_Title", resourceCulture);
            }
        }
        
        public static string PortView_ToggleButton_Enabled {
            get {
                return ResourceManager.GetString("PortView_ToggleButton_Enabled", resourceCulture);
            }
        }
        
        public static string PortView_ToggleButton_Disabled {
            get {
                return ResourceManager.GetString("PortView_ToggleButton_Disabled", resourceCulture);
            }
        }
        
        public static string ConnectionsPortsView_AddSerialCommand_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_AddSerialCommand_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsPortsView_AddTcpCommand_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_AddTcpCommand_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsPortsView_AddUdpCommand_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_AddUdpCommand_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsPortsView_Header_Title {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_Header_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsView_Header_Description {
            get {
                return ResourceManager.GetString("ConnectionsView_Header_Description", resourceCulture);
            }
        }
        
        public static string ConnectionsView_Header_Title {
            get {
                return ResourceManager.GetString("ConnectionsView_Header_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsPortsView_Header_Description {
            get {
                return ResourceManager.GetString("ConnectionsPortsView_Header_Description", resourceCulture);
            }
        }
        
        public static string DeviceBrowserView_Description {
            get {
                return ResourceManager.GetString("DeviceBrowserView_Description", resourceCulture);
            }
        }
        
        public static string DeviceBrowserView_Header {
            get {
                return ResourceManager.GetString("DeviceBrowserView_Header", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationView_HeartbeatRate_Description {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatRate_Description", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationView_HeartbeatRate_Header {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatRate_Header", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationView_HeartbeatTimeout_Description {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatTimeout_Description", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationView_HeartbeatTimeout_Header {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_HeartbeatTimeout_Header", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationView_SystemComponentId_Description {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_SystemComponentId_Description", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationView_SystemComponentId_Header {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationView_SystemComponentId_Header", resourceCulture);
            }
        }
        
        public static string MavlinkDeviceView_Mode_Name {
            get {
                return ResourceManager.GetString("MavlinkDeviceView_Mode_Name", resourceCulture);
            }
        }
        
        public static string MavlinkDeviceView_Rate_Name {
            get {
                return ResourceManager.GetString("MavlinkDeviceView_Rate_Name", resourceCulture);
            }
        }
        
        public static string MavlinkDeviceView_Status_Name {
            get {
                return ResourceManager.GetString("MavlinkDeviceView_Status_Name", resourceCulture);
            }
        }
        
        public static string TcpPortView_TcpIpAddress {
            get {
                return ResourceManager.GetString("TcpPortView_TcpIpAddress", resourceCulture);
            }
        }
        
        public static string TcpPortView_PortTitle {
            get {
                return ResourceManager.GetString("TcpPortView_PortTitle", resourceCulture);
            }
        }
        
        public static string TcpPortView_TcpIpPort {
            get {
                return ResourceManager.GetString("TcpPortView_TcpIpPort", resourceCulture);
            }
        }
        
        public static string UdpPortView_LocalIpAddress {
            get {
                return ResourceManager.GetString("UdpPortView_LocalIpAddress", resourceCulture);
            }
        }
        
        public static string UdpPortView_LocalPortName {
            get {
                return ResourceManager.GetString("UdpPortView_LocalPortName", resourceCulture);
            }
        }
        
        public static string UdpPortView_PortTitle {
            get {
                return ResourceManager.GetString("UdpPortView_PortTitle", resourceCulture);
            }
        }
        
        public static string UdpPortView_RemoteIpAddress {
            get {
                return ResourceManager.GetString("UdpPortView_RemoteIpAddress", resourceCulture);
            }
        }
        
        public static string UdpPortView_RemotePortName {
            get {
                return ResourceManager.GetString("UdpPortView_RemotePortName", resourceCulture);
            }
        }
        
        public static string UdpPortView_ToggleName {
            get {
                return ResourceManager.GetString("UdpPortView_ToggleName", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationViewModel_DeviceTimeout {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationViewModel_DeviceTimeout", resourceCulture);
            }
        }
        
        public static string ConnectionsIdentificationViewModel_ToString {
            get {
                return ResourceManager.GetString("ConnectionsIdentificationViewModel_ToString", resourceCulture);
            }
        }
        
        public static string PortViewModel_SkippedUnitTest {
            get {
                return ResourceManager.GetString("PortViewModel_SkippedUnitTest", resourceCulture);
            }
        }
        
        public static string TcpPortViewModel_Title {
            get {
                return ResourceManager.GetString("TcpPortViewModel_Title", resourceCulture);
            }
        }
        
        public static string TcpPortViewModel_ValidTitle {
            get {
                return ResourceManager.GetString("TcpPortViewModel_ValidTitle", resourceCulture);
            }
        }
        
        public static string TcpPortViewModel_ValidPort {
            get {
                return ResourceManager.GetString("TcpPortViewModel_ValidPort", resourceCulture);
            }
        }
        
        public static string TcpPortViewModel_ValidIpAddress {
            get {
                return ResourceManager.GetString("TcpPortViewModel_ValidIpAddress", resourceCulture);
            }
        }
        
        public static string TcpPortViewModel_LogService_Error {
            get {
                return ResourceManager.GetString("TcpPortViewModel_LogService_Error", resourceCulture);
            }
        }
        
        public static string UdpPortViewModel_ValidTitle {
            get {
                return ResourceManager.GetString("UdpPortViewModel_ValidTitle", resourceCulture);
            }
        }
        
        public static string UdpPortViewModel_ValidLocalIpAddress {
            get {
                return ResourceManager.GetString("UdpPortViewModel_ValidLocalIpAddress", resourceCulture);
            }
        }
        
        public static string UdpPortViewModel_ValidLocalPort {
            get {
                return ResourceManager.GetString("UdpPortViewModel_ValidLocalPort", resourceCulture);
            }
        }
        
        public static string UdpPortViewModel_ValidRemotePort {
            get {
                return ResourceManager.GetString("UdpPortViewModel_ValidRemotePort", resourceCulture);
            }
        }
        
        public static string UdpPortViewModel_ValidRemoteIpAddress {
            get {
                return ResourceManager.GetString("UdpPortViewModel_ValidRemoteIpAddress", resourceCulture);
            }
        }
        
        public static string UdpPortViewModel_Title {
            get {
                return ResourceManager.GetString("UdpPortViewModel_Title", resourceCulture);
            }
        }
        
        public static string PacketViewerShellMenuItem_Name {
            get {
                return ResourceManager.GetString("PacketViewerShellMenuItem_Name", resourceCulture);
            }
        }
        
        public static string LogMessageTypeHelper_GetDisplayName_Info {
            get {
                return ResourceManager.GetString("LogMessageTypeHelper_GetDisplayName_Info", resourceCulture);
            }
        }
        
        public static string LogMessageTypeHelper_GetDisplayName_Warning {
            get {
                return ResourceManager.GetString("LogMessageTypeHelper_GetDisplayName_Warning", resourceCulture);
            }
        }
        
        public static string LogMessageTypeHelper_GetDisplayName_Error {
            get {
                return ResourceManager.GetString("LogMessageTypeHelper_GetDisplayName_Error", resourceCulture);
            }
        }
        
        public static string PacketViewerView_CheckAll {
            get {
                return ResourceManager.GetString("PacketViewerView_CheckAll", resourceCulture);
            }
        }
        
        public static string PacketViewerView_PlayPause {
            get {
                return ResourceManager.GetString("PacketViewerView_PlayPause", resourceCulture);
            }
        }
        
        public static string PacketViewerView_ClearAll {
            get {
                return ResourceManager.GetString("PacketViewerView_ClearAll", resourceCulture);
            }
        }
        
        public static string PacketViewerView_Save {
            get {
                return ResourceManager.GetString("PacketViewerView_Save", resourceCulture);
            }
        }
        
        public static string Voltage_Unit {
            get {
                return ResourceManager.GetString("Voltage_Unit", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_EditDialogPort_Accept {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_EditDialogPort_Accept", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_EditSerialPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_EditSerialPortDialog_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_EditTcpPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_EditTcpPortDialog_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_EditUdpPortDialog_Title {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_EditUdpPortDialog_Title", resourceCulture);
            }
        }
        
        public static string ConnectionsViewModel_EditDialogPort_Cancel {
            get {
                return ResourceManager.GetString("ConnectionsViewModel_EditDialogPort_Cancel", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_By_ToolTip {
            get {
                return ResourceManager.GetString("LogMessagesPageView_By_ToolTip", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_ClearAllButton_ToolTip {
            get {
                return ResourceManager.GetString("LogMessagesPageView_ClearAllButton_ToolTip", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_PrevButton_ToolTip {
            get {
                return ResourceManager.GetString("LogMessagesPageView_PrevButton_ToolTip", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_NextButton_ToolTip {
            get {
                return ResourceManager.GetString("LogMessagesPageView_NextButton_ToolTip", resourceCulture);
            }
        }
        
        public static string LogMessagesPageView_RefreshButton_ToolTip {
            get {
                return ResourceManager.GetString("LogMessagesPageView_RefreshButton_ToolTip", resourceCulture);
            }
        }
        
        public static string LoggerView_ErrorFilter_Name {
            get {
                return ResourceManager.GetString("LoggerView_ErrorFilter_Name", resourceCulture);
            }
        }
        
        public static string LoggerView_InfoFilter_Name {
            get {
                return ResourceManager.GetString("LoggerView_InfoFilter_Name", resourceCulture);
            }
        }
        
        public static string LoggerView_WarningFilter_Name {
            get {
                return ResourceManager.GetString("LoggerView_WarningFilter_Name", resourceCulture);
            }
        }
        
        public static string LoggerView_TraceFilter_Name {
            get {
                return ResourceManager.GetString("LoggerView_TraceFilter_Name", resourceCulture);
            }
        }
        
        public static string SavedCoordsView_Header {
            get {
                return ResourceManager.GetString("SavedCoordsView_Header", resourceCulture);
            }
        }
        
        public static string SavedCoordsView_Description {
            get {
                return ResourceManager.GetString("SavedCoordsView_Description", resourceCulture);
            }
        }
        
        public static string SavedCoordsView_AddNewButton_Name {
            get {
                return ResourceManager.GetString("SavedCoordsView_AddNewButton_Name", resourceCulture);
            }
        }
        
        public static string SavedCoordsView_RemoveButton_Name {
            get {
                return ResourceManager.GetString("SavedCoordsView_RemoveButton_Name", resourceCulture);
            }
        }
        
        public static string SavedCoordsViewModel_AddNewItem_Title {
            get {
                return ResourceManager.GetString("SavedCoordsViewModel_AddNewItem_Title", resourceCulture);
            }
        }
        
        public static string SavedCoordsViewModel_AddNewItem_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SavedCoordsViewModel_AddNewItem_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string SavedCoordsViewModel_AddNewItem_CloseButtonText {
            get {
                return ResourceManager.GetString("SavedCoordsViewModel_AddNewItem_CloseButtonText", resourceCulture);
            }
        }
        
        public static string AddNewMapPointView_Latitude_Name {
            get {
                return ResourceManager.GetString("AddNewMapPointView_Latitude_Name", resourceCulture);
            }
        }
        
        public static string AddNewMapPointView_Longitude_Name {
            get {
                return ResourceManager.GetString("AddNewMapPointView_Longitude_Name", resourceCulture);
            }
        }
        
        public static string AddNewMapPointView_Altitude_Name {
            get {
                return ResourceManager.GetString("AddNewMapPointView_Altitude_Name", resourceCulture);
            }
        }
        
        public static string AddNewMapPointView_Accuracy_Name {
            get {
                return ResourceManager.GetString("AddNewMapPointView_Accuracy_Name", resourceCulture);
            }
        }
        
        public static string SavedCoordsViewModel_RemoveItem_Title {
            get {
                return ResourceManager.GetString("SavedCoordsViewModel_RemoveItem_Title", resourceCulture);
            }
        }
        
        public static string SavedCoordsViewModel_RemoveItem_PrimaryButtonText {
            get {
                return ResourceManager.GetString("SavedCoordsViewModel_RemoveItem_PrimaryButtonText", resourceCulture);
            }
        }
        
        public static string SavedCoordsViewModel_RemoveItem_CloseButtonText {
            get {
                return ResourceManager.GetString("SavedCoordsViewModel_RemoveItem_CloseButtonText", resourceCulture);
            }
        }
        
        public static string RemoveMapPointView_ConfirmationText {
            get {
                return ResourceManager.GetString("RemoveMapPointView_ConfirmationText", resourceCulture);
            }
        }
        
        public static string RemoveMapPointView_Point_Name {
            get {
                return ResourceManager.GetString("RemoveMapPointView_Point_Name", resourceCulture);
            }
        }
        
        public static string RemoveMapPointView_Latitude_Name {
            get {
                return ResourceManager.GetString("RemoveMapPointView_Latitude_Name", resourceCulture);
            }
        }
        
        public static string RemoveMapPointView_Longitude_Name {
            get {
                return ResourceManager.GetString("RemoveMapPointView_Longitude_Name", resourceCulture);
            }
        }
        
        public static string RemoveMapPointView_Altitude_Name {
            get {
                return ResourceManager.GetString("RemoveMapPointView_Altitude_Name", resourceCulture);
            }
        }
        
        public static string RemoveMapPointView_Accuracy_Name {
            get {
                return ResourceManager.GetString("RemoveMapPointView_Accuracy_Name", resourceCulture);
            }
        }
        
        public static string AddNewMapPointView_Point_Name {
            get {
                return ResourceManager.GetString("AddNewMapPointView_Point_Name", resourceCulture);
            }
        }
        
        public static string AddNewMapPointViewModel_Accuracy_ValidValue {
            get {
                return ResourceManager.GetString("AddNewMapPointViewModel_Accuracy_ValidValue", resourceCulture);
            }
        }
        
        public static string AddNewMapPointViewModel_Name_ValidValue {
            get {
                return ResourceManager.GetString("AddNewMapPointViewModel_Name_ValidValue", resourceCulture);
            }
        }
        
        public static string LoggerView_Clear_Name {
            get {
                return ResourceManager.GetString("LoggerView_Clear_Name", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SeparatorDialog_Title {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SeparatorDialog_Title", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SeparatorDialog_DialogPrimaryButton {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SeparatorDialog_DialogPrimaryButton", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SeparatorDialog_DialogSecondaryButton {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SeparatorDialog_DialogSecondaryButton", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SeparatorDialog_Coma {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SeparatorDialog_Coma", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SeparatorDialog_Semicolon {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SeparatorDialog_Semicolon", resourceCulture);
            }
        }
        
        public static string PacketViewerViewModel_SeparatorDialog_Tab {
            get {
                return ResourceManager.GetString("PacketViewerViewModel_SeparatorDialog_Tab", resourceCulture);
            }
        }
        
        public static string MapPageViewModel_RulerStartPoint_Description {
            get {
                return ResourceManager.GetString("MapPageViewModel_RulerStartPoint_Description", resourceCulture);
            }
        }
        
        public static string MapPageViewModel_RulerStopPoint_Description {
            get {
                return ResourceManager.GetString("MapPageViewModel_RulerStopPoint_Description", resourceCulture);
            }
        }
        
        public static string Ddm_InParts_Title {
            get {
                return ResourceManager.GetString("Ddm_InParts_Title", resourceCulture);
            }
        }
        
        public static string Ddm_Percent_Title {
            get {
                return ResourceManager.GetString("Ddm_Percent_Title", resourceCulture);
            }
        }
        
        public static string Ddm_Microamp_Title {
            get {
                return ResourceManager.GetString("Ddm_Microamp_Title", resourceCulture);
            }
        }
        
        public static string Ddm_µA_Unit {
            get {
                return ResourceManager.GetString("Ddm_µA_Unit", resourceCulture);
            }
        }
        
        public static string Ddm_MicroampRus_Title {
            get {
                return ResourceManager.GetString("Ddm_MicroampRus_Title", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_DdmLlz {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_DdmLlz", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModel_DdmLlzDescription {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModel_DdmLlzDescription", resourceCulture);
            }
        }
        
        public static string Power_Dbm_Title {
            get {
                return ResourceManager.GetString("Power_Dbm_Title", resourceCulture);
            }
        }
        
        public static string Power_Dbm_Unit {
            get {
                return ResourceManager.GetString("Power_Dbm_Unit", resourceCulture);
            }
        }
        
        public static string AmplitudeModulation_Percent_Title {
            get {
                return ResourceManager.GetString("AmplitudeModulation_Percent_Title", resourceCulture);
            }
        }
        
        public static string AmplitudeModulation_InParts_Unit {
            get {
                return ResourceManager.GetString("AmplitudeModulation_InParts_Unit", resourceCulture);
            }
        }
        
        public static string Frequency_Hertz_Title {
            get {
                return ResourceManager.GetString("Frequency_Hertz_Title", resourceCulture);
            }
        }
        
        public static string Frequency_Kilohertz_Title {
            get {
                return ResourceManager.GetString("Frequency_Kilohertz_Title", resourceCulture);
            }
        }
        
        public static string Frequency_Megahertz_Title {
            get {
                return ResourceManager.GetString("Frequency_Megahertz_Title", resourceCulture);
            }
        }
        
        public static string Frequency_Gigahertz_Title {
            get {
                return ResourceManager.GetString("Frequency_Gigahertz_Title", resourceCulture);
            }
        }
        
        public static string Frequency_Hertz_Unit {
            get {
                return ResourceManager.GetString("Frequency_Hertz_Unit", resourceCulture);
            }
        }
        
        public static string Frequency_Kilohertz_Unit {
            get {
                return ResourceManager.GetString("Frequency_Kilohertz_Unit", resourceCulture);
            }
        }
        
        public static string Frequency_Megahertz_Unit {
            get {
                return ResourceManager.GetString("Frequency_Megahertz_Unit", resourceCulture);
            }
        }
        
        public static string Frequency_Gigahertz_Unit {
            get {
                return ResourceManager.GetString("Frequency_Gigahertz_Unit", resourceCulture);
            }
        }
        
        public static string Phase_Degree_Title {
            get {
                return ResourceManager.GetString("Phase_Degree_Title", resourceCulture);
            }
        }
        
        public static string Phase_Radian_Title {
            get {
                return ResourceManager.GetString("Phase_Radian_Title", resourceCulture);
            }
        }
        
        public static string Phase_Radian_Unit {
            get {
                return ResourceManager.GetString("Phase_Radian_Unit", resourceCulture);
            }
        }
        
        public static string MapSettingsView_MapSettings_Header {
            get {
                return ResourceManager.GetString("MapSettingsView_MapSettings_Header", resourceCulture);
            }
        }
        
        public static string MapSettingsView_MapSettings_Description {
            get {
                return ResourceManager.GetString("MapSettingsView_MapSettings_Description", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModelDdmGp {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModelDdmGp", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModelDdmGpDescription {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModelDdmGpDescription", resourceCulture);
            }
        }
        
        public static string BearingDegreeTitle {
            get {
                return ResourceManager.GetString("BearingDegreeTitle", resourceCulture);
            }
        }
        
        public static string Temperature_Celsius_Title {
            get {
                return ResourceManager.GetString("Temperature_Celsius_Title", resourceCulture);
            }
        }
        
        public static string Temperature_Farenheit_Title {
            get {
                return ResourceManager.GetString("Temperature_Farenheit_Title", resourceCulture);
            }
        }
        
        public static string Temperature_Kelvin_Title {
            get {
                return ResourceManager.GetString("Temperature_Kelvin_Title", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModelTemperature {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModelTemperature", resourceCulture);
            }
        }
        
        public static string MeasureUnitsSettingsViewModelTemperatureDescription {
            get {
                return ResourceManager.GetString("MeasureUnitsSettingsViewModelTemperatureDescription", resourceCulture);
            }
        }
    }
}
