//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Core.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string ByteSize_BytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_BytesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string ByteSize_GigabytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_GigabytesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string ByteSize_KilobytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_KilobytesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string ByteSize_MegabytesUnit {
            get {
                return ResourceManager.GetString("ByteSize_MegabytesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/s.
        /// </summary>
        public static string BytesRate_BytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_BytesPerSecondUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB/s.
        /// </summary>
        public static string BytesRate_GigaBytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_GigaBytesPerSecondUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB/s.
        /// </summary>
        public static string BytesRate_KiloBytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_KiloBytesPerSecondUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB/s.
        /// </summary>
        public static string BytesRate_MegaBytesPerSecondUnit {
            get {
                return ResourceManager.GetString("BytesRate_MegaBytesPerSecondUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Common_NotAvailable {
            get {
                return ResourceManager.GetString("Common_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight mode.
        /// </summary>
        public static string FlightShellMenuItem_Name {
            get {
                return ResourceManager.GetString("FlightShellMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GHz.
        /// </summary>
        public static string ItemsRate_GigaHerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_GigaHerzUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        public static string ItemsRate_HerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_HerzUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHz.
        /// </summary>
        public static string ItemsRate_KiloHerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_KiloHerzUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHz.
        /// </summary>
        public static string ItemsRate_MegaHerzUnit {
            get {
                return ResourceManager.GetString("ItemsRate_MegaHerzUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission planing.
        /// </summary>
        public static string PlaningShellMenuItem_Name {
            get {
                return ResourceManager.GetString("PlaningShellMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsShellMenuProvider_SettingsShellMenuProvider_Settings {
            get {
                return ResourceManager.GetString("SettingsShellMenuProvider_SettingsShellMenuProvider_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current application theme..
        /// </summary>
        public static string SettingsThemeViewModel_ChangeThemeDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_ChangeThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsThemeViewModel_CurrentLanguage {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current application language. The changes will be applied after a restart..
        /// </summary>
        public static string SettingsThemeViewModel_CurrentLanguageDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsThemeViewModel_CurrentTheme {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow direction.
        /// </summary>
        public static string SettingsThemeViewModel_FlowDirection {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current application flow direction..
        /// </summary>
        public static string SettingsThemeViewModel_FlowDirectionDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_FlowDirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ThemeService_FlowDirections_LeftToRight {
            get {
                return ResourceManager.GetString("ThemeService_FlowDirections_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        public static string ThemeService_FlowDirections_RightToLeft {
            get {
                return ResourceManager.GetString("ThemeService_FlowDirections_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string ThemeService_Themes_Contrast {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeService_Themes_Dark {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeService_Themes_Light {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Light", resourceCulture);
            }
        }
    }
}
