//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Core.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight mode.
        /// </summary>
        public static string FlightShellMenuItem_Name {
            get {
                return ResourceManager.GetString("FlightShellMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change current map provider for application.
        /// </summary>
        public static string MapSettingsView_MapProvider_Description {
            get {
                return ResourceManager.GetString("MapSettingsView_MapProvider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Provider.
        /// </summary>
        public static string MapSettingsView_MapProvider_Header {
            get {
                return ResourceManager.GetString("MapSettingsView_MapProvider_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MapSettingsView_MapsInfo_ButtonName {
            get {
                return ResourceManager.GetString("MapSettingsView_MapsInfo_ButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps location and size.
        /// </summary>
        public static string MapSettingsView_MapsInfo_Description {
            get {
                return ResourceManager.GetString("MapSettingsView_MapsInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps Info.
        /// </summary>
        public static string MapSettingsView_MapsInfo_Header {
            get {
                return ResourceManager.GetString("MapSettingsView_MapsInfo_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission planing.
        /// </summary>
        public static string PlaningShellMenuItem_Name {
            get {
                return ResourceManager.GetString("PlaningShellMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsShellMenuProvider_SettingsShellMenuProvider_Settings {
            get {
                return ResourceManager.GetString("SettingsShellMenuProvider_SettingsShellMenuProvider_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current application theme..
        /// </summary>
        public static string SettingsThemeViewModel_ChangeThemeDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_ChangeThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsThemeViewModel_CurrentLanguage {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current application language. The changes will be applied after a restart..
        /// </summary>
        public static string SettingsThemeViewModel_CurrentLanguageDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsThemeViewModel_CurrentTheme {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_CurrentTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow direction.
        /// </summary>
        public static string SettingsThemeViewModel_FlowDirection {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_FlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current application flow direction..
        /// </summary>
        public static string SettingsThemeViewModel_FlowDirectionDescription {
            get {
                return ResourceManager.GetString("SettingsThemeViewModel_FlowDirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ThemeService_FlowDirections_LeftToRight {
            get {
                return ResourceManager.GetString("ThemeService_FlowDirections_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RightToLeft.
        /// </summary>
        public static string ThemeService_FlowDirections_RightToLeft {
            get {
                return ResourceManager.GetString("ThemeService_FlowDirections_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string ThemeService_Themes_Contrast {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeService_Themes_Dark {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeService_Themes_Light {
            get {
                return ResourceManager.GetString("ThemeService_Themes_Light", resourceCulture);
            }
        }
    }
}
