//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asv.Drones.Gui.Sdr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asv.Drones.Gui.Sdr.RS", typeof(RS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot OS.
        /// </summary>
        public static string FlightSdrView_SystemControlAction_Reboot_Title {
            get {
                return ResourceManager.GetString("FlightSdrView_SystemControlAction_Reboot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown OS.
        /// </summary>
        public static string FlightSdrView_SystemControlAction_Shutdown_Title {
            get {
                return ResourceManager.GetString("FlightSdrView_SystemControlAction_Shutdown_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than 0.
        /// </summary>
        public static string FlightSdrViewModel_Frequency_Validation_ErrorMessage {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_Frequency_Validation_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string FlightSdrViewModel_RecordStartDialog_PrimarryButton_Name {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_RecordStartDialog_PrimarryButton_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FlightSdrViewModel_RecordStartDialog_SecondaryButton_Name {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_RecordStartDialog_SecondaryButton_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FlightSdrViewModel_RecordStartDialog_Title {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_RecordStartDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to set payload mode.
        /// </summary>
        public static string FlightSdrViewModel_StartRecord_Error_Message {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_StartRecord_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec start.
        /// </summary>
        public static string FlightSdrViewModel_StartRecord_Error_Sender {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_StartRecord_Error_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to set payload mode.
        /// </summary>
        public static string FlightSdrViewModel_StopRecord_Error_Message {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_StopRecord_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rec stop.
        /// </summary>
        public static string FlightSdrViewModel_StopRecord_Error_Sender {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_StopRecord_Error_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload.
        /// </summary>
        public static string FlightSdrViewModel_Title {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to set payload mode.
        /// </summary>
        public static string FlightSdrViewModel_UpdateMode_Error_Message {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_UpdateMode_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set mode.
        /// </summary>
        public static string FlightSdrViewModel_UpdateMode_Error_Sender {
            get {
                return ResourceManager.GetString("FlightSdrViewModel_UpdateMode_Error_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDR link quality.
        /// </summary>
        public static string LinkQualitySdrRttView_ToolTip {
            get {
                return ResourceManager.GetString("LinkQualitySdrRttView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM 150 Hz.
        /// </summary>
        public static string LlzSdrRttViewModel_AM_150_Hz_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_AM_150_Hz_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM 90 Hz.
        /// </summary>
        public static string LlzSdrRttViewModel_AM_90_Hz_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_AM_90_Hz_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR.
        /// </summary>
        public static string LlzSdrRttViewModel_Clr_Header {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_Clr_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR.
        /// </summary>
        public static string LlzSdrRttViewModel_CLRPower_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_CLRPower_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRS.
        /// </summary>
        public static string LlzSdrRttViewModel_Crs_Header {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_Crs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRS.
        /// </summary>
        public static string LlzSdrRttViewModel_CRSPower_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_CRSPower_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDM.
        /// </summary>
        public static string LlzSdrRttViewModel_DDM_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_DDM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field strength.
        /// </summary>
        public static string LlzSdrRttViewModel_FieldStrength_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_FieldStrength_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μV/m.
        /// </summary>
        public static string LLzSdrRttViewModel_FieldStrength_Units {
            get {
                return ResourceManager.GetString("LLzSdrRttViewModel_FieldStrength_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq 150 Hz.
        /// </summary>
        public static string LlzSdrRttViewModel_Freq_150_Hz_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_Freq_150_Hz_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq 90 Hz.
        /// </summary>
        public static string LlzSdrRttViewModel_Freq_90_Hz_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_Freq_90_Hz_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq..
        /// </summary>
        public static string LlzSdrRttViewModel_MainFrequency_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_MainFrequency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTime.
        /// </summary>
        public static string LlzSdrRttViewModel_MeasureTime_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_MeasureTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string LLzSdrRttViewModel_MeasureTime_Units {
            get {
                return ResourceManager.GetString("LLzSdrRttViewModel_MeasureTime_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDM.
        /// </summary>
        public static string LlzSdrRttViewModel_SDM_Title {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModel_SDM_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N\A.
        /// </summary>
        public static string LLzSdrRttViewModel_ValueNotAvailable {
            get {
                return ResourceManager.GetString("LLzSdrRttViewModel_ValueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch..
        /// </summary>
        public static string LlzSdrRttViewModelChannelTitle {
            get {
                return ResourceManager.GetString("LlzSdrRttViewModelChannelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string RecordStartView_AddButton_Title {
            get {
                return ResourceManager.GetString("RecordStartView_AddButton_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record name (required).
        /// </summary>
        public static string RecordStartView_RecordName_Title {
            get {
                return ResourceManager.GetString("RecordStartView_RecordName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new record name.
        /// </summary>
        public static string RecordStartView_RecordName_Watermark {
            get {
                return ResourceManager.GetString("RecordStartView_RecordName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record tags (optional).
        /// </summary>
        public static string RecordStartView_RecordTags_Title {
            get {
                return ResourceManager.GetString("RecordStartView_RecordTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new tag name.
        /// </summary>
        public static string RecordStartView_TagName_Watermark {
            get {
                return ResourceManager.GetString("RecordStartView_TagName_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new tag value.
        /// </summary>
        public static string RecordStartView_TagValue_Watermark {
            get {
                return ResourceManager.GetString("RecordStartView_TagValue_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid record name.
        /// </summary>
        public static string RecordStartViewModel_RecordName_Validation_ErrorMessage {
            get {
                return ResourceManager.GetString("RecordStartViewModel_RecordName_Validation_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid tag name.
        /// </summary>
        public static string RecordStartViewModel_TagName_Validation_ErrorMessage {
            get {
                return ResourceManager.GetString("RecordStartViewModel_TagName_Validation_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not valid Float64 value!.
        /// </summary>
        public static string RecordStartViewModel_TagValue_Float64_ErrorMessage {
            get {
                return ResourceManager.GetString("RecordStartViewModel_TagValue_Float64_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not valid Int64 value!.
        /// </summary>
        public static string RecordStartViewModel_TagValue_Int64_ErrorMessage {
            get {
                return ResourceManager.GetString("RecordStartViewModel_TagValue_Int64_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length must be &lt; 9, and contain only ascii-chars!.
        /// </summary>
        public static string RecordStartViewModel_TagValue_String8_ErrorMessage {
            get {
                return ResourceManager.GetString("RecordStartViewModel_TagValue_String8_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not valid UInt64 value!.
        /// </summary>
        public static string RecordStartViewModel_TagValue_UInt64_ErrorMessage {
            get {
                return ResourceManager.GetString("RecordStartViewModel_TagValue_UInt64_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string SdrPayloadBrowserView_Sort_By_Date {
            get {
                return ResourceManager.GetString("SdrPayloadBrowserView_Sort_By_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SdrPayloadBrowserView_Sort_By_Name {
            get {
                return ResourceManager.GetString("SdrPayloadBrowserView_Sort_By_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        public static string SdrPayloadBrowserView_Sort_Title {
            get {
                return ResourceManager.GetString("SdrPayloadBrowserView_Sort_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N\A.
        /// </summary>
        public static string SdrRttItem_ValueNotAvailable {
            get {
                return ResourceManager.GetString("SdrRttItem_ValueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Code.
        /// </summary>
        public static string SdrRttViewModel_ID_Code_Title {
            get {
                return ResourceManager.GetString("SdrRttViewModel_ID_Code_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string SdrRttViewModel_Main_Header {
            get {
                return ResourceManager.GetString("SdrRttViewModel_Main_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF.
        /// </summary>
        public static string SdrRttViewModel_Rf_Header {
            get {
                return ResourceManager.GetString("SdrRttViewModel_Rf_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string SdrRttViewModel_SumPower_Title {
            get {
                return ResourceManager.GetString("SdrRttViewModel_SumPower_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SdrStoreBrowserViewModel_SearchWatermark {
            get {
                return ResourceManager.GetString("SdrStoreBrowserViewModel_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total samples: {0}.
        /// </summary>
        public static string SdrStoreBrowserViewModel_TotalFileSamples {
            get {
                return ResourceManager.GetString("SdrStoreBrowserViewModel_TotalFileSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0}.
        /// </summary>
        public static string SdrStoreBrowserViewModel_TotalFileSize {
            get {
                return ResourceManager.GetString("SdrStoreBrowserViewModel_TotalFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string SdrStoreEntityViewModel_DeleteDialog_Content {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_DeleteDialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SdrStoreEntityViewModel_DeleteDialog_PrimaryButton {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_DeleteDialog_PrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SdrStoreEntityViewModel_DeleteDialog_SecondaryButton {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_DeleteDialog_SecondaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        public static string SdrStoreEntityViewModel_DeleteDialog_Title {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_DeleteDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string SdrStoreEntityViewModel_MoveDialog_PrimaryButton {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_MoveDialog_PrimaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SdrStoreEntityViewModel_MoveDialog_SecondaryButton {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_MoveDialog_SecondaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change location.
        /// </summary>
        public static string SdrStoreEntityViewModel_MoveDialog_Title {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_MoveDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid record name.
        /// </summary>
        public static string SdrStoreEntityViewModel_Name_Validation_ErrorMessage {
            get {
                return ResourceManager.GetString("SdrStoreEntityViewModel_Name_Validation_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field strength.
        /// </summary>
        public static string VorSdrRttViewModel_FieldStrength_Title {
            get {
                return ResourceManager.GetString("VorSdrRttViewModel_FieldStrength_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to μV/m.
        /// </summary>
        public static string VorSdrRttViewModel_FieldStrength_Units {
            get {
                return ResourceManager.GetString("VorSdrRttViewModel_FieldStrength_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string VorSdrRttViewModel_Main_Header {
            get {
                return ResourceManager.GetString("VorSdrRttViewModel_Main_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq..
        /// </summary>
        public static string VorSdrRttViewModel_MainFrequency_Title {
            get {
                return ResourceManager.GetString("VorSdrRttViewModel_MainFrequency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTime.
        /// </summary>
        public static string VorSdrRttViewModel_MeasureTime_Title {
            get {
                return ResourceManager.GetString("VorSdrRttViewModel_MeasureTime_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string VorSdrRttViewModel_MeasureTime_Units {
            get {
                return ResourceManager.GetString("VorSdrRttViewModel_MeasureTime_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM 30 Hz.
        /// </summary>
        public static string VorSdrRttViewModelAM30HzTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelAM30HzTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM 9960 Hz.
        /// </summary>
        public static string VorSdrRttViewModelAM9960HzTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelAM9960HzTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        public static string VorSdrRttViewModelBearingTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelBearingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch..
        /// </summary>
        public static string VorSdrRttViewModelChannelTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelChannelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM-Deviation.
        /// </summary>
        public static string VorSdrRttViewModelFMDeviationTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelFMDeviationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FM Index.
        /// </summary>
        public static string VorSdrRttViewModelFMIndexTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelFMIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq 30 Hz.
        /// </summary>
        public static string VorSdrRttViewModelFreq30HzTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelFreq30HzTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq 9960 Hz.
        /// </summary>
        public static string VorSdrRttViewModelFreq9960HzTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelFreq9960HzTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq FM 30.
        /// </summary>
        public static string VorSdrRttViewModelFreqFM30Title {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelFreqFM30Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lev.
        /// </summary>
        public static string VorSdrRttViewModelPowerTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelPowerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice AM.
        /// </summary>
        public static string VorSdrRttViewModelVoiceAmTitle {
            get {
                return ResourceManager.GetString("VorSdrRttViewModelVoiceAmTitle", resourceCulture);
            }
        }
    }
}
