name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIHUB_NUGET_AUTH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.create-release-notes.outputs.release-notes }}
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') }}
          
      - name: Trigger MacOS workflow
        uses: actions/github-script@v6
        with:
          script: |
              const response = await github.actions.createWorkflowDispatch({
                owner: '${{ secrets.USER_NAME }}',
                repo: 'asv-drones',
                workflow_id: 'build-macos-arm64.yml', // имя файла workflow
                ref: 'feat/mac-os-arm64-deployment',
              })
              console.log(response)

      - name: Trigger Windows workflow
        uses: actions/github-script@v6
        with:
          script: |
              const response = await github.actions.createWorkflowDispatch({
                owner: '${{ secrets.USER_NAME }}',
                repo: 'asv-drones',
                workflow_id: 'BuildForWindows.yml',
                ref: 'feat/mac-os-arm64-deployment',
              })
              console.log(response)
          